### ISSUE TITLE
make orma-vn-api db docker container include data

### ISSUE THREAD

**Issue by maxgrossman** [orma/openroads-vn-analytics#101]
The current db contianer used in [orma-vn-api](https://github.com/orma/openroads-vn-api/tree/master/db) does not populate the database with any data. It seems that a scaffold for making it do so lives in [openroads-data](https://github.com/orma/openroads-data/tree/develop/db).

We could reconfigure the current db container to do so by using the above scaffold with csvs generated by a db dump from the current orma vn database.

I could follow this proces for the admins using (orma-vn-boundaries)[https://github.com/orma/openroads-vn-boundaries/tree/feature/clean-geometries]. So too could the new rlp tables be generated from the work in (the new rlp pr)
[https://github.com/orma/openroads-vn-api/tree/feature/ingest-rlp-geometries].

@olafveerman, @dereklieu - thoughts?

**Comment by dereklieu** [comment]
I think it's a good approach. It only takes us to write the script and seed the data once, and in return we get to run unit tests against real-ish data whenever we need to develop a new feature, for example the admin routes.

@maxgrossman did you have an alternative approach in mind?

Btw if you want to make markdown links it goes [link text](link url).

**Comment by maxgrossman** [comment]
@dereklieu - no other ideas for me. I think setting up the db to have test data is the way to go. Then any `docker compose up` command will make a db with pre-populated data. 

thanks for the markdown tips too 🏄

**Comment by maxgrossman** [comment]
I just pushed to the db-with-data [branch](https://github.com/orma/openroads-vn-api/tree/feature/db-with-data) so we can compose the service with fixture data. 

To spin up a service with fixture data run `yarn docker-start-fixture` on that branch (for now)

I think this method for populating the db with fixture db might make sense for populating with real data and simplify how we partition between populating the db.

The method is as follows:

1. Dump the db tables to a zip file that sits in an s3 bucket
2. Make 2 docker-compose files (one just `docker-compose.yml`, the other `docker-compose-fixture.yml`)
3. cast yarn commands that build, then `up` the service using either one of the above two configs
  - each config's build object is as follows (and is what determines if we are populating with fixture or production data

```
version: "3"
services:
  db:
    build: 
      context: ./db
      args: 
        - seed= # fixture or production
```

   - if seed=fixture, it populates with seed data.
   -  if production, it populates with prod data.

if we are worried about wanting also to be able to compose without any data, then (dare I say) we can make a 3rd compose file and update the part of the db's dockerfile that adds data to only insert data conditional on there being a `SEED` environmental variable

**Comment by maxgrossman** [comment]
edit for the above. rather than different config files, just make different services in the same config file...

**Comment by mileswwatkins** [comment]
Two thoughts:

- Won't we always want there to be admin data ingested? I don't think we need a separate Compose setup for that contingency.
- For test data for RoadLabPro, this should only ever be in a testing database, never in a production

The way this was done [in ORMA–PH](https://github.com/orma/openroads-data/tree/develop/db/extensions/test) was by having a special Dockerfile that built with seed data in it. I'd be in favor of this; in phase 2(?), we can add seed road data for local dev (and have a different Compose YAML or service, eg), but even then I don't think we should alter the production Compose service for the database, just have a separate one?

Actually, maybe this is something that @kamicut could look at for ten minutes and make a final rec on.

**Comment by maxgrossman** [comment]
@mileswwatkins - just for an update the fixture data was added  [here] (https://github.com/orma/openroads-vn-api/pull/12). This ticket remains open until we get the lamba function work all settled.

**Comment by maxgrossman** [comment]
@matthewhanson - per the above, all work for this ticket except working lambda functions are done. So assigning to you and we can close when lambda/migration work is complete.

**Comment by mileswwatkins** [comment]
What's the status on this @matthewhanson @matthewhanson?

**Comment by matthewhanson** [comment]
@mileswwatkins I think I have all the pieces, just need to run some tests, will try and get it done today.

**Comment by matthewhanson** [comment]
@mileswwatkins I ran into some problems getting this to work. We've got the scripts to run this as a manual step, can we push automatic migrations to phase 2?

**Comment by mileswwatkins** [comment]
Sounds good @matthewhanson!
