### ISSUE TITLE
Export data in CSV (WKT)

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#103]
The current road network exports are in GeoJSON. Check feasibility of implementing export to CSV in WKT still in phase 1.

**Comment by maxgrossman** [comment]
closed with openroad-tiler's [#4](https://github.com/orma/openroads-vn-tiler/pull/4)

**Comment by mileswwatkins** [comment]
I'm taking this the rest of the way, as part of https://github.com/orma/openroads-vn-analytics/issues/125
