### ISSUE TITLE
Adding PCR analysis to dashboard

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#104]
@Charlesfox1 is working on a [set of scripts](https://github.com/Charlesfox1/RoadLabPro_Utils) that derive tabular analytics per VPROM including: poverty score, link criticality, and roughness. There are 5 indicators in total, each normalized on a 0-1 scale. There is also an overall score, that's composed by the 5 indicators.

It'd be fairly straightforward to import these in the db, and serve the stats through the API for display in the analytics dashboard.
We should assess the lift of:

- creating a small script that imports data into a VPROMM stats table
- developing the API endpoint
- including this on the dashboard

@maxgrossman @ricardomestre

**Comment by mileswwatkins** [comment]
This tabular properties-for-a-VPRoMMS-road-ID information can be ingested using the tabular data API endpoint; no new code needed on that end. These will be stored as properties in the `road-properties` db table. Then we can surface these in the dashboards: https://github.com/orma/openroads-vn-analytics/issues/113.

**Comment by mileswwatkins** [comment]
@olafveerman, the question is more, whose responsibility is running Charles's scripts, and uploading the tabular-by-VPRoMMS-road-ID results to our API endpoint?

**Comment by olafveerman** [comment]
It would be ideal to do a first run with @Charlesfox1, possibly in Vn?

**Comment by mileswwatkins** [comment]
[Sounds good to me!](https://youtu.be/O_HyZ5aW76c?t=1m4s)

**Comment by Charlesfox1** [comment]
Sounds good to me as well! Also coming to your offices tomorrow for the 2pm - so could try then?

C
