### ISSUE TITLE
Zoom to VPROMM

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#105]
Add functionality on the dashboard that allows a user to zoom to a VPROMM on the map.

**Comment by mileswwatkins** [comment]
@olafveerman, so, in the Analytics tables, a user can click on a button for each road, to get taken to that road on the Editor view? Explore view? How do you envision we handle this if there are multiple geometries that are tagged with that particular VPRoMMS road ID?

**Comment by maxgrossman** [comment]
@miles @olafveerman  - we have a [globZoom](https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/reducers/reducer.js#L328) object as part of our state tree. Both maps set their initial zoom from this object.

We also have an API [endpoint](https://github.com/orma/openroads-vn-api/blob/master/routes/way.js#L147) for getting bbox of a given vpromms. 

On 'click' of a vpromms, we fire the action to update the globZoom, which would send you to either map at the desired zoom.

**Comment by mileswwatkins** [comment]
Sounds like a good flow. Let's make the user go to the Explore view.
