### ISSUE TITLE
Make the CSV dumps _routable_, and make sure they include necessary fields

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#125]
Use Charles's script to create by-province and by-district dumps of VPRoMMS-road-ID-tagged roads, instead of the current dumps which aren't pumped through Charles's script.

Attributes needed are:

Line_Geometry | ID | iri_mean | iri_med | iri_min | iri_max | VPROMMS_ID | length
-- | -- | -- | -- | -- | -- | -- | --

- `ID` is a unique arbitrary number
- additional fields may exist without causing issues

**Comment by mileswwatkins** [comment]
Status update:

I tried re-implementing the logic of Charles's script using PostGIS, but found that `ST_APPROXIMATEMEDIALAXIS` takes a very long time to run (didn't complete for the country's roads within 15 minutes). [Here's the working code](https://gist.github.com/mileswwatkins/34d29b80a68344ed92cb3a93a47c164f).

Then, I did a little work with [Charles's existing script](https://github.com/Charlesfox1/RoadLabPro_Utils/blob/master/Network_Clean.py), trying to make our database dump to a format that his script expects. However, after talking with him, apparently there's an outstanding software issue (also with finding the medial axis) that prevents it from functioning for certain districts (and presumably their parent provinces); this issue is outstanding in the Shapely GitHub org. The working districts would take about 20 minutes each to run.

cc @Charlesfox1 @olafveerman

**Comment by Charlesfox1** [comment]
This is all true. The expensive bit is finding the centerline for the multipolygon object. Thereafter it's a breeze, as long as 'shapely.ops.split' works. 

It's currently an issue with shapely - but I think you guys are good enough at coding to get round it with some sort of try / except clause inserted into the split function. I implore you to try it out! 

C
