### ISSUE TITLE
Tag all AWS services with project tag

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#136]
More of a reminder to tag all AWS services with `Project`: `openroads-vn`

**Comment by mileswwatkins** [comment]
Are we good on this one, @matthewhanson?

**Comment by matthewhanson** [comment]
everything has been tagged

**Comment by olafveerman** [comment]
@matthewhanson The EC2 wasn't tagged. Is there a way to set it in the CloudFormation template?

**Comment by matthewhanson** [comment]
I had tagged it manually just before, but yes it can be set in CF, which I'm doing now.  Actually it occurred to me that the tag might not propagate through updates if not set in CF.  I'm just making sure all resources are tagged - iam users, security groups, etc

**Comment by matthewhanson** [comment]
Ok, everything has been tagged and it's in the CF template now on develop.
