### ISSUE TITLE
Tabular ingest doesn't handle unicode characters correctly

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#138]
Maybe switch off of that D3-DSV library, its CSV parsing leaves a lot to be desired.

**Comment by danielfdsilva** [comment]
@mileswwatkins Problem was that `curl` was uploading the data as a single string disregarding line breaks.
Use `--data-binary` instead of `-d` and it'll be fine.

```
curl --data-binary @road_properties.csv -H 'Content-Type: text/csv' http://localhost/properties/roads/tabular
```

**Comment by mileswwatkins** [comment]
Confirmed, closed by documentation update https://github.com/orma/openroads-vn-api/commit/059c2d89928bd206f9f261e77ff3c9042db6f0d4
