### ISSUE TITLE
Handling multiple VPROMMS when de-duping

### ISSUE THREAD

**Issue by dereklieu** [orma/openroads-vn-analytics#140]
When we are choosing a canonical geometry for a road (and deleting non-canonical geometries) what should we do with the to-be-deleted VPROMMS ids if they don't match the canonical?

@mileswwatkins

**Comment by mileswwatkins** [comment]
The VPRoMMS road IDs that would be deleted are just `tag`s on the production geometry; the core data for VPRoMMS road IDs is stored in `road_properties` and `point_properties`, so no worries about just chucking tags if their geometries are getting deleted.

**Comment by mileswwatkins** [comment]
@dereklieu, remind me, is this completed?

**Comment by dereklieu** [comment]
Right now, if you select a bunch of roads to delete ('dedupe') using the task UI, those roads just get deleted along with their tags, which include vpromms. Let me know if there should be different behavior.

**Comment by mileswwatkins** [comment]
I think the ideal UX would be to have the interface to show a list of all the `or_vpromms` values in the selected roads (ordered by frequency), and let the user pick which `or_vpromms` is applied to the final geometry. Or maybe auto-selecting the modal `or_vpromms`.

But your solution works for now!

**Comment by geohacker** [comment]
We did this in https://github.com/orma/openroads-vn-analytics/pull/368
