### ISSUE TITLE
Roads in Explore view are not displaying as colored by IRI

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#158]
In http://ec2-52-55-132-50.compute-1.amazonaws.com/#/en/explore the tiles are not being colored by IRI (ie, a continuous numeric surface-roughness scale); all the roads are just black. Two possible causes, off the top of my head:

1. There is a front-end error in the `openroads-vn-analytics` React components that's preventing the style-tiles-by-IRI step from occurring in the Explore view. Nothing shows up in my console right now, but something like this could definitely be the issue; definitely easier to test this.
2. The IRI information is not getting properly stitched on to the features in the tiles. Thus, the tiles don't have the property to be colored by in the first place. This should be happening in `openroads-vn-tiler` worker code, specifically https://github.com/orma/openroads-vn-tiler/blob/develop/scripts/make-analysis-and-display.sh which dumps the point (ie, IRI) and line (ie, geometry) data and calls https://github.com/orma/openroads-vn-tiler/blob/develop/scripts/conflate-points-lines.js to apply the IRI point data to the geometries.

cc @olafveerman

**Comment by danielfdsilva** [comment]
The `iri` property is present in the ´properties` of the features, but it is in string format. I'm guessing that it doesn't play well with the color stops.
I wasn't able to find any way to change this property client side. Since the data comes from the vector tile it's not possible got get the source data and modify it.

It's probably worth a shot to store the value as a number in the tiles.

**Comment by mileswwatkins** [comment]
Gotcha. Can you try casting the IRI to `Numeric()` in https://github.com/orma/openroads-vn-tiler/blob/develop/scripts/conflate-points-lines.js, and see if that does the trick? Thanks for the digging!

**Comment by danielfdsilva** [comment]
@mileswwatkins tried to do as you suggested, but even after uploading the tiles to mapbox they were not updated in the frontend. I even added a new property to ensure the information I was seeing is new but to no avail.
Could this be a cache situation?

**Comment by mileswwatkins** [comment]
Were the tiles showing numeric values locally? That would answer the caching issue. It's also possible that (since the tiles are re-pushed by production every 5 minutes) that what you were seeing bad tiles even though you'd just uploaded "good" tiles. ie, your locally-generated numeric tiles were being overwritten.

**Comment by olafveerman** [comment]
Fixes seem to have done it. IRI is back: 

![image](https://user-images.githubusercontent.com/751330/31321737-1bc07e44-ac58-11e7-8bbf-cdce62d4b8f7.png)
