### ISSUE TITLE
VProMM doesn't zoom to its bbox

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#162]
Regression. Clicking on a road id in the analytics table, doesn't make explore zoom to the extent of the road:

```
mapbox-gl.js:150 Uncaught (in promise) Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]
```

**Comment by maxgrossman** [comment]
@olafveerman - fixing bug #160 seems to have taken care of this.

**Comment by olafveerman** [comment]
Closed through: https://github.com/orma/openroads-vn-api/commit/aff43d0a5dcbad5e6aa309319f5e4050a3befd6e

**Comment by danielfdsilva** [comment]
this is not fixed. Looking into it
