### ISSUE TITLE
Analytics page is slow to load

### ISSUE THREAD

**Issue by danielfdsilva** [orma/openroads-vn-analytics#168]
The main analytic page takes a long time to load, and there isn't any indication that something is going on. The page looks blank and unresponsive.
There's a resource being loaded that is 3.3mb and takes ~15seconds.
It looks to me that these are all the roads. Is it necessary to load everything upfront?

<img width="654" alt="image" src="https://user-images.githubusercontent.com/1090606/31318229-c19d3422-ac46-11e7-844b-de3ea4f90a2d.png">

**Comment by maxgrossman** [comment]
@danielfdsilva - this is due to the old loading all vpromms data at once. I've since refactored and the load is much faster. These changes are in my new pr to which you are assigned.
