### ISSUE TITLE
Add data-export functionality

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#17]
- [ ] create worker task to dump network as GeoJSON, by-province (ie, characters 4 and 5 of VPRoMMS road ID), to public-read ACL S3 bucket
- [ ] add data-download button to each province's Analytics page, to download the dump

**Comment by mileswwatkins** [comment]
Maybe the letter codes are sub-province admin codes, but they should all still map M:1 to the provinces.

**Comment by mileswwatkins** [comment]
Ugh, yes!! The VPRoMMS documentation has, in Annex 1, a full map of the two-letter codes (apparently "districts"), and the province name (and two-digit province code) that it is within. And it's all stored within a Pages.app spreadsheet, so it's structured.

Here it is: https://www.dropbox.com/s/79voqnx70u7hvei/Vietnam%20PRoMMS%20Road%20Inventory%20and%20Condition%20Surveys%202011-06-21.docx?dl=0

**Comment by mileswwatkins** [comment]
Since the files could be quite large (not now, but later on), you may want to use stream processing to perform the filtering and writing-to-file:

- library: https://github.com/node-geojson/geojson-stream
- example use for filtering: https://github.com/developmentseed/merck-data/blob/76bc5ad18a9a3fbbd15698641c2a7dd5011e766a/bin/filter-zip5-geojson.js

**Comment by maxgrossman** [comment]
thanks for the resources @mileswwatkins
