### ISSUE TITLE
Load missing VProMMs

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#173]
Load missing VProMMs

cc @PCDuc

**Comment by olafveerman** [comment]
Will be done later this week by @mileswwatkins

**Comment by mileswwatkins** [comment]
Donezo, lookin' gooooood. Save for an issue (I believe) regarding crosswalking Nam Dinh's ID, which I'll spin off for @maxgrossman.

<img width="926" alt="screen shot 2017-10-11 at 10 45 26" src="https://user-images.githubusercontent.com/4959135/31421403-65d38f60-ae71-11e7-83c2-0795ed551b93.png">

**Comment by geohacker** [comment]
@mileswwatkins looks like we've some mismatches in the uploaded roads reported by @PCDuc. Could you note here how the ingestion was done so we can go back and inspect? Thank you!

**Comment by mileswwatkins** [comment]
@geohacker, I believe that Max or I created a crosswalk in the front-end repo. The source for this crosswalk should've been in the VPRoMMS spec PDF, at a table towards the end; I think I copied that into a spreadsheet and cleaned it up manually a bit.
