### ISSUE TITLE
simplify reducer

### ISSUE THREAD

**Issue by maxgrossman** [orma/openroads-vn-analytics#176]
I've made one long reducer file with at times inconsistently named reducers. 
Going to take some time later on today to clean this up (split action specific reducers into their own files, fix up names, and remove some legacy functions where they exist)

**Comment by mileswwatkins** [comment]
Sharded by @jameslaneconkling https://github.com/orma/openroads-vn-analytics/tree/develop/app/assets/scripts/redux/modules
