### ISSUE TITLE
validate all endpoints

### ISSUE THREAD

**Issue by maxgrossman** [orma/openroads-vn-analytics#177]
@danielfdsilva made the suggestion to validate our routes' parameters and queries. Going to take care of this for a few routes I just built today, then work on validation throughout the api.

**Comment by mileswwatkins** [comment]
@maxgrossman, update on this? This seems like it'd be solved better using unit tests, no?

**Comment by mileswwatkins** [comment]
(This ticket isn't a huge priority in the immediate future.)
