### ISSUE TITLE
add pagination to analytics tables

### ISSUE THREAD

**Issue by maxgrossman** [orma/openroads-vn-analytics#179]

**Comment by dereklieu** [comment]
Not sure if you're implementing this in the API or the front-end, but if you're doing it on the front-end, you can look at this snippet from the field data desktop app: https://github.com/osmlab/field-data-coordinator/blob/master/src/ui/data/Observation-Table.jsx#L59-L81

**Comment by maxgrossman** [comment]
@dereklieu - thanks for the snippet. My plan (run by @kamicut in a qv) includes additions to both front end and the api. The goal here is not just to keep tables reasonable in length, but also reduce the amount of data fetched.

Anyway, the plan is: 

1) extend [this endpoint](https://github.com/orma/openroads-vn-api/blob/develop/routes/admin.js#L292) to do index/offset queries
2) trigger those queries with clicks to page buttons in a list, inspired by what you shared
3) update state tree w/new road index data element that acts as the offset in the sql queries
