### ISSUE TITLE
Ingest national road geometries

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#185]
National roads aren't tracked as part of the VPRoMMS system. To incorporate them in the short term, @PCDuc will give us a shapefile, and I'll ingest it as a vanilla OSM changeset.

These roads should be uneditable (ie, geometry-locked), have the `national` road ownership property, and I'll tag them with an additional source property so that we'll be able to identify and delete them once we have a more formalized system for ingesting national roads.

cc @olafveerman

**Comment by mileswwatkins** [comment]
Here is the file for the TH province national roads: [NatRoad-TH-VBD.RAR.zip](https://github.com/orma/openroads-vn-analytics/files/1385158/NatRoad-TH-VBD.RAR.zip)

Waiting on Lao Cai from Sarah.

**Comment by mileswwatkins** [comment]
@olafveerman, steps to be done:

- [ ] strip any unnecessary properties, if you'd like; these won't matter much, will just be visible in Editor view
- [ ] add an `or_responsibility` property to them, so that they style correctly in Editor
- [ ] convert the shapefile an OSM changeset using `ogr2osm`
- [ ] upload the OSM changeset using the ORMA API

**Comment by mileswwatkins** [comment]
This is being reconsidered in the immediate term, waiting for a better approach. Delaying to next phase.

**Comment by mileswwatkins** [comment]
Current goal of this deliverable, following conversation with @olafveerman and @sarahantos tonight:

- do not assign national roads IDs
- do not ingest national roads into the OSM production geometries table
- do not show national road information in Analytics
- store and display national roads as an uneditable basemap-y layer in Editor and Explore
- _do_ include national roads in the routable CSV dumps by-admin-area

This will allow updated national roads files to be drop-in replacements at a later date.

**Comment by mileswwatkins** [comment]
Current line-item:

Ability to view and download national roads in the system. This will mean that the network viewed in the explorer Map will show the national roads, and the network dumps (also used for analytics) will also have the national roads. _(World Bank to provide this national road by Dec 1)_

**Comment by geohacker** [comment]
> Ability to view and download national roads in the system. This will mean that the network viewed in the explorer Map will show the national roads, and the network dumps (also used for analytics) will also have the national roads.

@mileswwatkins sorry if my question doesn't make much sense - reading the backscroll here it sounds to me that we no longer have to ingest this to the ORMA db but in order to have them show on the explorer map create vector tiles?

**Comment by mileswwatkins** [comment]
Correct! So, we'll store the national roads separately (as a private file on S3 for now, probably), and then mix them in to the network when we generate vector tiles and network dumps, but nowhere else.

**Comment by mileswwatkins** [comment]
Converted the national roads file to GeoJSON and stored (privately) on the production dumps bucket, at `private-fixture-data/National_network.geojson`.

**Comment by geohacker** [comment]
Let's reopen this. We're still a few steps away from having this fully integrated and might look for other methods of data processing.

**Comment by geohacker** [comment]
We've a workflow for this now https://github.com/orma/openroads-vn-api#whole-of-network-import
