### ISSUE TITLE
When switching between Explore and Edit maps, maintain zoom and coordinates

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#20]
When switching from one view to the other, using the nav bar, the user's zoom and coordinates should be preserved.

**Comment by mileswwatkins** [comment]
@danielfdsilva, Olaf had said that you built some listeners into the iD IFrame; is this something that you'd have time to implement either Friday or next week? Or is it easy, and it'd be easier for everyone for you to just tell us how to implement it? Either way, help would be much appreciated!

**Comment by mileswwatkins** [comment]
Seems like we can just use the querystring parameters to both fetch and set in the iD/raster view _and_ in the GL/vector view.

**Comment by maxgrossman** [comment]
Now in production with #56
