### ISSUE TITLE
Delete existing RLP geometries, and re-upload

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#204]
RLP upload now includes cleaning, which is not present when we uploaded the data currently in the platform. This'll remove the many erroneous long-straight segments that we see now.

<img width="285" alt="screen shot 2017-10-12 at 14 16 40" src="https://user-images.githubusercontent.com/4959135/31483765-fbfea66e-af57-11e7-878d-64b25a812e2b.png">

**Comment by mileswwatkins** [comment]
Steps needed to fix this and https://github.com/orma/openroads-vn-analytics/issues/187:

- [ ] `TRUNCATE` all OSM tables, and the field data geometry table
- [ ] `DELETE` all records from `road_properties` that have field data information (eg, `length`, `iri_mean`, etc), but not any DRVN Excel properties (eg, `Start Point Name`)
- [ ] `UPDATE` the `id`s in `road_properties` to the correct ten characters in length
- [ ] re-upload all the RLP field data via the API

**Comment by mileswwatkins** [comment]
@dereklieu, can you skim this, maybe run the SQL block (with the `ROLLBACK;`!!!) against the production database, and tell me whether it looks reasonable? It's executing the steps I laid out above. This is just for my sanity; I've looked at it a bunch and am pretty sure it does what I need it to.

```
BEGIN;

TRUNCATE changesets,
  nodes,
  ways,
  relations,
  field_data_geometries,
  point_properties,
  tasks
CASCADE;

DELETE FROM road_properties
WHERE properties -> 'Start Point Name' IS NULL AND
  properties -> 'iri_mean' IS NOT NULL;

DELETE FROM road_properties AS ninedigit
USING road_properties AS tendigit
WHERE tendigit.id = CONCAT(SUBSTRING(ninedigit.id FROM 1 FOR 5), '0', SUBSTRING(ninedigit.id FROM 6 FOR 4)) AND
  LENGTH(ninedigit.id) = 9;

UPDATE road_properties
  SET id = CONCAT(SUBSTRING(id FROM 1 FOR 5), '0', SUBSTRING(id FROM 6 FOR 4))
  WHERE LENGTH(id) = 9;

ROLLBACK;
```

(but with `COMMIT;` instead of the rollback line above, when I finally run it for real)

Then I'll run these two lines to re-ingest the field geometries:

```
curl --form file=@"all-field-data.zip" http://api.openroads-vn.com/fielddata/properties/rlp
curl --form file=@"all-field-data.zip" http://api.openroads-vn.com/fielddata/geometries/rlp
```

**Comment by mileswwatkins** [comment]
If it looks good, I'll run this all tomorrow morning, first thing.

**Comment by dereklieu** [comment]
@mileswwatkins one note is that the osm stuff is all stored in `current_nodes` an `current_ways`, not `nodes` and `ways`. 

It's probably that there aren't any relations yet since the upload *shouldn't* automatically create them, but they would also be `current_relations`.

Are you concerned about deleting tags? They'll just reference entities that no longer exist. They are `way_tags` and `node_tags` I believe.

Finally, you should delete `way_nodes` as well, since those are what link ways and nodes.

The rest look good, I didn't run it against a production db but I did against a local one and didn't get any errors.

**Comment by mileswwatkins** [comment]
Thanks Derek! The `CASCADE`'d truncate takes care of the `current_*` tables, so I think we're good. When I first had gone to write a statement containing all of the OSM tables, it was very long ;)

**Comment by mileswwatkins** [comment]
<img width="478" alt="screen shot 2017-10-13 at 09 05 42" src="https://user-images.githubusercontent.com/4959135/31527177-b5fb4336-aff5-11e7-892b-c88a8aaa32ef.png">

All better!
