### ISSUE TITLE
Geometry properties' key names not shown in Tasks, on-road-hover

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#210]
<img width="795" alt="screen shot 2017-10-13 at 11 50 56" src="https://user-images.githubusercontent.com/4959135/31530804-0add44c8-b00d-11e7-9519-22208380a7ca.png">

`key` should be replaced with the actual key name!

**Comment by geohacker** [comment]
This looks like it's fixed:

![image](https://user-images.githubusercontent.com/371666/35457229-28b2a24a-02a6-11e8-84fe-eee340dfd4ba.png)
