### ISSUE TITLE
Show road _name_ in Tasks map, not just ID

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#211]
Right now, the Tasks map exposes the properties of the geometry; that is, it shows all `current_way_tag` key-values:

<img width="795" alt="screen shot 2017-10-13 at 11 50 56" src="https://user-images.githubusercontent.com/4959135/31530772-d977ec94-b00c-11e7-9d94-aec9a43e16f1.png">

Ideally, it should show some/all `road_properties` for the given VPRoMMS road ID form that road's `current_way_tag`'s `or_vpromms`. Specifically, there's interest in seeing road name (property key `Road Name` from the DRVN spreadsheets).

Request from DRVN.

**Comment by geohacker** [comment]
This is one of the fixes for https://github.com/orma/openroads-vn-analytics/issues/371#issuecomment-360856403
