### ISSUE TITLE
After two geometries have been de-duped in Tasks, leftover points show up in Editor

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#215]
Maybe this is because the `current_ways` record is deleted, but the `current_nodes` records are not? Makes Editor pretty messy:

<img width="930" alt="screen shot 2017-10-13 at 13 15 49" src="https://user-images.githubusercontent.com/4959135/31532660-c977a3b4-b018-11e7-9864-d60226589660.png">

**Comment by dereklieu** [comment]
Hah nice. I can fix this today.

**Comment by mileswwatkins** [comment]
@dereklieu, points are popping up after _intersection_ actions on Tasks, not just de-duping. Probably requires additions here.

**Comment by mileswwatkins** [comment]
As part of this bugfix (beyond fixing the code for Tasks), can you also do a one-off manual delete of all nodes in the DB that aren't related to any way? Those should all be leftover artifacts.

**Comment by dereklieu** [comment]
Yes, sorry I've been late on this. I can try to get a fix this week, but next is more likely.

**Comment by mileswwatkins** [comment]
'sokay! @olafveerman and I have just been talking about tying up the tail of Phase 1.

**Comment by dereklieu** [comment]
@mileswwatkins pr amended. I've written a handful of SQL statements in my life and am not well equipped to write even the simple one deleting orphaned nodes. I also noticed I can't connect directly to the production db as it's host-restricted, makes sense. If you or someone else could take care of writing and performing the deletion, that would be better.

**Comment by mileswwatkins** [comment]
Still have manual SQL deletion to do, on my/James's end.

**Comment by mileswwatkins** [comment]
```
SELECT count(*)
FROM current_nodes as cn
LEFT JOIN current_way_nodes as cwn
ON cn.id = cwn.node_id
WHERE cwn.node_id IS NULL AND
cn.id IS NOT NULL;
```

Returns a count of `3072`. These are the believed bad nodes.

To confirm, I checked that all rows in `current_nodes` had a non-null `id`. I also confirmed that my join was good, by testing that the following query had a lot of results (~41k):

```
SELECT count(*)
FROM current_nodes as cn
LEFT JOIN current_way_nodes as cwn
ON cn.id = cwn.node_id
WHERE cwn.node_id IS NOT NULL AND
cn.id IS NOT NULL;
```

I tested this deletion query within a (rolled-back) transaction, and it is catching the same 3k records as the earlier `SELECT`. This is the query I'm going to execute on the production data:

```
DELETE FROM current_nodes
WHERE id NOT IN (
	SELECT node_id
	FROM current_way_nodes
);
```
