### ISSUE TITLE
Delete identically-duplicate roads from the OSM tables

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#216]
Turns out that some of the field data in the RLP directories I had was duplicated, resulting in identical duplicates in the database. This causes problems for the Tasks view and Editor views, as it's completely opaque as to which road is being clicked, or _why_ an identical path remains when a road is deleted in Tasks or modified in Editor.

Eg:

![dups](https://user-images.githubusercontent.com/4959135/31535692-2edfa5c8-b026-11e7-98ed-257c5dbb75b7.gif)

@olafveerman, I'm assigning this to you, but I expect that this is a better fit for @kamicut or @dereklieu who've worked with OSM SQL queries and models more than you or I. I believe this has to be done between now and Sunday.

I'm not sure whether this involves modifying `current_ways`, `current_way_nodes`, or something else in the OSM schema. Also don't know whether this has to be done with a changeset, or if we can modify the DB directly.

(I've already deleted the duplicate `field_data_geometries` and `point_properties` records.)

In the long run, this will be guarded against by https://github.com/orma/openroads-vn-analytics/issues/131

**Comment by olafveerman** [comment]
@mileswwatkins Wouldn't it be easier to do a re-import of the RLP data?

**Comment by mileswwatkins** [comment]
It's going to be decent amount of work either way. The RLP _data_ is identical, but the folder names are not, so I'll have to, like, hash the contents of every folder in the field data to find dups.

**Comment by mileswwatkins** [comment]
This can be done alongside https://github.com/orma/openroads-vn-analytics/issues/131; moving to Phase 2

**Comment by mileswwatkins** [comment]
So, I believe there are 7 duplicate roads, based on this query:

```
SELECT cwn.node_id,
	sequence_id,
	count(*)
FROM current_ways AS cw
LEFT JOIN current_way_nodes AS cwn
ON cw.id = cwn.way_id
WHERE cwn.node_id IS NOT NULL
GROUP BY cwn.node_id,
	cwn.sequence_id
HAVING count(*) > 1 AND
	sequence_id = 0
ORDER BY cwn.node_id,
	cwn.sequence_id;
```

There are 7 duplicated first-in-sequence nodes:

```
 node_id
---------
   36753
   37411
   38109
   38628
   51424
   51507
   56119
(7 rows)
```

I confirmed (using a higher `sequence_id` value) that these weren't just coincidental-same-start-point-but-actually-different-roads-entirely situations.

These start nodes map to these 14 ways:

```
SELECT cw.id
FROM current_ways AS cw
LEFT JOIN current_way_nodes AS cwn
ON cw.id = cwn.way_id
WHERE node_id IN (SELECT node_id FROM dup_node_ids) AND
	sequence_id = 0;

 id
-----
 383
 394
 407
 408
 409
 411
 412
 414
 495
 496
 551
 552
 553
 554
(14 rows)
```

Looks like the tags are the same for these duplicates:

```
SELECT cw.id,
	cwt.k,
	cwt.v
FROM current_ways AS cw
LEFT JOIN current_way_nodes AS cwn
ON cw.id = cwn.way_id
LEFT JOIN current_way_tags AS cwt
ON cw.id = cwt.way_id
WHERE cwn.node_id IN (SELECT node_id FROM dup_node_ids) AND
	cwn.sequence_id = 0;

 id  |     k      |     v
-----+------------+------------
 383 | or_vpromms | 022BX00014
 383 | highway    | road
 394 | or_vpromms | 022BX00014
 394 | highway    | road
 407 | or_vpromms | 212TH00036
 407 | highway    | road
 408 | or_vpromms | 212TH00023
 408 | highway    | road
 409 | or_vpromms | 212TH00023
 409 | highway    | road
 411 | or_vpromms | 212TH00023
 411 | highway    | road
 412 | or_vpromms | 212TH00023
 412 | highway    | road
 414 | or_vpromms | 212TH00036
 414 | highway    | road
 495 | or_vpromms | 214TT00012
 495 | highway    | road
 496 | or_vpromms | 214TT00012
 496 | highway    | road
 551 | or_vpromms | 214TT00012
 551 | highway    | road
 552 | or_vpromms | 214TT00012
 552 | highway    | road
 553 | or_vpromms | 212TH00008
 553 | highway    | road
 554 | or_vpromms | 212TH00008
 554 | highway    | road
(28 rows)
```

So before I do manual deletes of each duplicate (as identified by having the same `or_vpromms`), I'll just make sure that they share all their nodes, eg:

```
SELECT ARRAY(
	SELECT node_id
	FROM current_way_nodes
	WHERE way_id = 383
) = ARRAY(
	SELECT node_id
	FROM current_way_nodes
	WHERE way_id = 394
);

 ?column?
----------
 t
(1 row)
```

Niiiice. So, I've decided to manually delete ways `394` (dup of `383`), `414` (dup of `407`), `411` (dup of `408`), `412` (dup of `409`), `551` (dup of `495`), `552` (dup of `496`), and `554` (dup of `553`).

Unfortunately, have to delete from all relevant tables; no fun `CASCADE` set up for me ;(

```
BEGIN;

	DELETE FROM current_way_nodes
	WHERE way_id IN (394, 414, 411, 412, 551, 552, 554);

	DELETE FROM current_way_tags
	WHERE way_id IN (394, 414, 411, 412, 551, 552, 554);

	DELETE FROM tasks
	WHERE way_id IN (394, 414, 411, 412, 551, 552, 554);

	DELETE FROM current_ways
	WHERE id IN (394, 414, 411, 412, 551, 552, 554);

COMMIT;
```

Resulting in output:

```
DELETE 1778
DELETE 14
DELETE 7
DELETE 7
```

All done!
