### ISSUE TITLE
Sorting does not work on Analytics tables

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#220]
Hitting a column header to trigger sort does nothing, and does not seem to execute anything in React, according to the developer console.

![no-sort](https://user-images.githubusercontent.com/4959135/31573213-7ed14f44-b0e1-11e7-8211-ff77e007143a.gif)

**Comment by mileswwatkins** [comment]
I believe this is a new bug since your most recent PR (which fixed many separate issues).

**Comment by maxgrossman** [comment]
@mileswwatkins the initial sort bug was closed with #256, but our discussions reveal the need for better ui solution.

The goal here is to make a new ui component that will sort the ids by different properties (existence of field data, maybe the length of road, others..) and reset the page to page 1.

Doing this would require: 

1. new api routes that mimic [`admin/roads`](https://github.com/orma/openroads-vn-api/blob/b381fa1e0c8ea32157152bdc7eb3a555cfd0742f/routes/admin.js#L281) and its complimentary [`admin/roads/properties`](https://github.com/orma/openroads-vn-api/blob/b381fa1e0c8ea32157152bdc7eb3a555cfd0742f/routes/admin.js#L332) using an offset of 0

2. paginating back to the 1st page
