### ISSUE TITLE
Simplify point-and-click RoadLabPro ingest

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#232]
In the short term, we have two different endpoints for ingesting RLP data (one for properties, one for geometries; see API docs). Accordingly, we have to have two buttons for point-and-click upload in the Uploads view. This is probably confusing for long-term use; either the endpoints should be unified in the API, or there should be a new route that triggers both of the RLP ingest handlers.

Additionally, right now the point-and-click file upload is made directly to the API endpoint, so the user is redirected to the API response which is in a pretty verbose JSON format. This should be papered over using React, to just show the user an upload progress indicator, and then a success/failure(+reason for failure) in-line, based on the API response.

https://github.com/orma/openroads-vn-analytics/blob/master/app/assets/scripts/views/upload.js

cc @olafveerman

**Comment by mileswwatkins** [comment]
The current interface is working, and this isn't a pressing item (ie, not in the ToR), so moving it to the backlog.

**Comment by geohacker** [comment]
Looks like as expected this has caused fair bit of confusion in the field. Throwing this into Phase 4.
