### ISSUE TITLE
Search suggestion (and thus full functionality) broken when in Vietnamese language

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#233]
No suggestions are listed at all.

**Comment by maxgrossman** [comment]
@miles - `name_vn`, the field for Vietnamese lang, are blank strings in the admin boundaries tables! Just need to update the tables and this should be handled.

**Comment by mileswwatkins** [comment]
Note that it's also breaking for Vietnamese-language VPRoMMS ID search.

**Comment by mileswwatkins** [comment]
Max successfully updated the database, fixing this.
