### ISSUE TITLE
In Tasks, allow way for users to see and tag roads without (or with invalid) VPRoMMS road IDs

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#235]
Including number of roads that are still missing VPRoMMS road IDs. There should be a way to mark road as "legitimately has no VPRoMMS road IDs" or the like, since 1) national roads and 2) some minor roads will _never_ have VPRoMMS road IDs (since the system only applies to provincial through local roads, that have been manually assigned those IDs).

**Comment by geohacker** [comment]
This was fixed in https://github.com/orma/openroads-vn-analytics/pull/368
