### ISSUE TITLE
Change "Analytics" view header to a different term

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#243]
@PCDuc, reply here to tell us what term we should use instead!

Maybe "Tabular" or "Completeness" or "Assets"? Apparently "Dashboard" doesn't translate.

Since we're integrating heavier analytics in Phase 2, we need to change this term to avoid confusion.

**Comment by PCDuc** [comment]
I think "Statistic' is a more relevant term when translate to Vietnamese.

**Comment by mileswwatkins** [comment]
Apparently word from on-high is "Assets," so I'm going to switch to that.
