### ISSUE TITLE
Handle bi-directional field data collection, for major roads with dual carriageways

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#247]
For major roads that are separated carriageways going each way, such as major highways, maintenance might be done separately in one side versus the other. Therefore, while we might be able to handle a single _geometry_, we'd have to store and display IRI and other quality metrics separately for each side.

**Comment by geohacker** [comment]
I think the most straightforward way here - and also something that [OSM widely uses](https://wiki.openstreetmap.org/wiki/Talk:Key:highway) - is to have two geometries.
