### ISSUE TITLE
Create by-admin-area user accounts

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#248]
These accounts should have geo-limited access…

- …to make changes in editor
- …to view and edit and download roads in analytics
- …maybe to view roads in explore
- …to only be shown tasks that affect their roads

@sarahantos, do you think these accounts should be by-province? By-district? Any other dimension of account restriction that I'm not thinking of?

**Comment by sarahantos** [comment]
I think we are going to have to draft a matrix of what a National, provincial, district, and possibly commune level person can do on the system. we might also divide these users into viewers and editors

**Comment by mileswwatkins** [comment]
Authentication is another big question here; do we run our own auth, or use OSM auth, or a third party service like Auth0? And thinking through password reset flows, etc.

**Comment by mileswwatkins** [comment]
@olafveerman, an idea: we use Location Services to identify where a user is when they make edits. Still just have a single login for the platform, for now. This gives us pretty good attribution (and we were just going to have one account per province, anyway), and is way quicker to accomplish than formal user accounts.

If DRVN wants editor/non-editor accounts, then we could do that with two different website deployments, or something.

**Comment by geohacker** [comment]
This should be covered in the upcoming research if we do it #353.
