### ISSUE TITLE
Add ability to create, update, and delete road IDs

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#253]
Provincial users should be able to create, alter, and delete VPRoMMS road IDs in the platform. This will affect which road IDs are considered "valid" for the purposes of ingest; road IDs that are not whitelisted this way will be rejected during the upload.

(Right now, if a user uploads tabular data or RLP data that contain road IDs that aren't in `road_properties` already, it creates new rows for them, which is improper.)

This probably requires a new endpoint, and UI updates in the Assets view.

cc https://github.com/orma/openroads-vn-analytics/issues/236

**Comment by mileswwatkins** [comment]
- Create: `INSERT` a new row into `road_properties`, with an empty `properties` value (ie, `{})
- Delete: `DELETE` that ID's row from `road_properties`. This'll also require you to set `road_id` to `NULL` for all related rows in `field_data_geometries` and `point_properties`, since they reference `road_properties.id` as a foreign key.
- Update: Check that the provided ID isn't already present in `road_properties`, to make sure there's no `PRIMARY KEY` collision. If it isn't already present, then `UPDATE` that ID's row in `road_properties` with the new `id` value. This'll also require you to update the IDs in `field_data_geometries` and `road_properties`. Also, update all rows in `current_way_tags` (OSM-schema table) where  `or_vpromms` is the `k` and the `v` is the road's old `id`.

**Comment by mileswwatkins** [comment]
Also! If you're creating or deleting, make sure that the road ID that the user is trying to create is valid! That means it must match this RegEx: `^\d{3}([A-ZĐa-zđ]{2}|00)\d{5}$` AND the road ID must contain the admin ID of the province page (or district page) that's being viewed.

That second clause is confusing, so let me explain. In the front-end, when you navigate to `/#/en/assets/401`, it fetches its road list using the API route `/field/roads?province=21`. (`401` is the admin code for the province in the shapefiles, and `21` is the admin code for the province in VPRoMMS.) On this page, if a user creates an ID, it should be within this province; the ID should start with `21`, thus matching `^21\d([A-ZĐa-zđ]{2}|00)\d{5}$`.

If a user is on a _district_ Assets webpage, say `/#/en/assets/401/40119`, then it will fetch roads based on the API request to route `/field/roads?province=21&district=TT`. Creating/updating a road ID within this page should only use IDs within the province; they should match the pattern `^21\dTT\d{5}$`.

Let me know if this makes sense!

**Comment by jameslaneconkling** [comment]
@mileswwatkins yeah, makes sense.
