### ISSUE TITLE
Search suggestions should only include roads that have geometries

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#263]
continuing from https://github.com/orma/openroads-vn-analytics/pull/258#issuecomment-340519693

**Comment by mileswwatkins** [comment]
@jameslaneconkling, later this week (when you're done with property CRUD), can you see if this relates to your two remaining tasks (#311 and #270)?

**Comment by geohacker** [comment]
Hah I was wondering why the search was a bit wonky but this explains why some of the searches in iD lands up to just a bbox.
