### ISSUE TITLE
Clarify which road was zoomed to, when navigating or using search

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#270]
When a user zooms to a particular VPRoMMS road ID using search functionality, visually indicate which path(s) constitute that road. (Currently, zooming to a road ID via search works, but it’s unclear which line represents the road in question.)

**Comment by mileswwatkins** [comment]
This should also cover non-search navigation to a particular road, such as when a user clicks on a road's ID in Assets view.

**Comment by mileswwatkins** [comment]
This is now solved for Explore view (vector tiles). @jameslaneconkling is looking into suggested solutions for Editor view (raster tiles, `iD`).

**Comment by jameslaneconkling** [comment]
iD can receive a [gpx parameter](https://github.com/openstreetmap/iD/blob/master/API.md), which could act as an overlay.  So one approach to getting this to work for iD would be to create a new api endpoint that serves roads as gpx.  There's already a `/properties/roads/:id.geojson`, so could fit naturally as `/properties/roads/:id.gpx`, if desired.

**Comment by geohacker** [comment]
Does all the orma road geometries get assigned a macrocosm ID? In which case the ideal way I can think would be to map the vprommid to macrocosm id and passing this down to the iD like `/#id=w563` - this will not only highlight the road but also open the edit mode which expands the tag selected etc.

@kamicut is this a possibility?

**Comment by geohacker** [comment]
I think my proposal above would work if we manage to add:

* [ ] export a set of related way tags in the /properties/roads/:road_id API end point by querying `current_way_tags` table for all related way ids.
* [ ] passing that into iD here https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/views/editor.js#L54
 * [ ] in case of no way ids, fall back to bbox with an alert (or not). and in case of no geometry, do nothing.

**Comment by geohacker** [comment]
I managed to get the way ID go into the the iD [editor URL within the iframe](https://github.com/orma/openroads-vn-analytics/blob/feature/search-road-select/app/assets/scripts/views/editor.js#L116) but it looks like to me that iD is clearing the hash on init and then setting it? So we're losing the `#id=`

@danielfdsilva do you happen to remember what the changes are to [iD's default hash handling](https://github.com/orma/openroads-vn-iD/blob/master/js/id/behavior/hash.js)? Thank you!

cc @kamicut

**Comment by danielfdsilva** [comment]
@geohacker As far as I remember was not easy to send info to iD through the url. iD cleans the url and only keeps the properties it sees fit. Some of them are used on init and then discarded.
What did you want to do?

**Comment by geohacker** [comment]
@danielfdsilva thank you for your response! what I'd like is to pass the feature id slug into the hash like `#id=w685` - this will make iD zoom into that feature, and select it for editing which will solve this ticket for us. Thoughts?

**Comment by danielfdsilva** [comment]
@geohacker that should be enough (it tries to load an id here https://github.com/orma/openroads-vn-iD/blob/master/js/id/behavior/hash.js#L85), maybe you need to do an additional check in the `hashchange` function?
I'd just `console.log` around to see what's happening.

**Comment by geohacker** [comment]
@danielfdsilva right that's what I thought too. okay let me dig a bit and get back. thank you! ✌️

**Comment by jameslaneconkling** [comment]
@geohacker can't speak to iD throwing away params, but in case iD does not natively have hightlight-by-id functionality, I was earlier hypothesizing that you could pass it a [gpx](https://github.com/openstreetmap/iD/blob/master/API.md) parameter that points to and endpoint that serves a single road as a gpx file.  There's already a route that serves a single road as geojson, so it would just be a matter of creating a new route that handles the gpx extension.

This still wouldn't solve the problem of zoom-to, though.

**Comment by geohacker** [comment]
Looks like inside the iframe iD doesn't do a render when the `#id` is set on search but sets the map view properly. 

@jameslaneconkling thank you! I'm trying to stay away from writing another spatial end point since we should already have a way id that we can pass into the editor. Regardless, using the gpx url param will still need iD to handle the hash properly which it isn't doing right now :-/

**Comment by geohacker** [comment]
@danielfdsilva's hunch that the `#id` changes are only set on load was correct. So I plugged that in in this PR https://github.com/orma/openroads-vn-iD/pull/39/files

I'm going to make bbox update as a fallback.
