### ISSUE TITLE
Display CVTS as an alternate basemap option in Editor and Explore maps

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#272]
World Bank will provide a single-time-period geo-referenced CVTS raster file, by December 1. This Commercial Vehicle Traffic Survey data will help show where roads receive the most wear.

**Comment by mileswwatkins** [comment]
Awaiting layer delivery from @Charlesfox1 in the next few weeks.

**Comment by mileswwatkins** [comment]
So, @geohacker, once Charles delivers the layer, you'll have to:

- [ ] tile it
- [ ] host these raster tiles, preferably on S3
- [ ] add a toggle to display CVTS tiles on the Editor view (ie, in the https://github.com/orma/openroads-vn-iD repo)
- [ ] add a toggle to display CVTS tiles on the vector-tile view (ie, in the `openroads-vn-analytics` repo)

And by "display," it could be as a basemap in and of itself, or potentially a layer _above_ the basemap and _below_ the roads.

This may require a new legend entry in one or both of the map views.

@olafveerman is probably a good point of contact on this question.

**Comment by mileswwatkins** [comment]
Oh, also @geohacker: If @Charlesfox1 doesn't have a chance to deliver the CVTS raster to Devseed in time for this task to be performed in Phase 3, then talk with @sarahantos about delaying this one deliverable item.

**Comment by geohacker** [comment]
_punting for a bit while the dataset is being prepared_

**Comment by geohacker** [comment]
This is done!
