### ISSUE TITLE
language changes don't trigger a rerender on /explore

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#279]
Looks like the `shouldComponentUpdate` check is blocking the rerender ([here](https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/views/explore.js#L110-L113)): 

```javascript
  shouldComponentUpdate: function (nextProps) {
    if (nextProps.vprommsBbox.length === 0) { return false; }
    return true;
  },
```

@mileswwatkins  @maxgrossman is the `shouldUpdate` optimization necessary here?  If not, I'll remove.  If it is, then it needs to be aware of route.

**Comment by mileswwatkins** [comment]
I'd use your judgment on this. I think that the BBox issue was to handle searches that resulted in a null response (ie, searching for the road resulted in no BBox returned). Otherwise, the map would try to zoom to a null BBox, which would cause problems in the UX.
