### ISSUE TITLE
Explore page screws up language on refresh

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#280]
* navigate to `/explore` when language is Vietnamese
* refresh page
* click anywhere in the header

Language state is now inconsistent.  URL continues to think the language is set to Vietnamese, but much of the content now rendered in English.

Would appear that the language state is being set in a component lifecycle prop.

**Comment by mileswwatkins** [comment]
https://github.com/orma/openroads-vn-analytics/pull/304
