### ISSUE TITLE
Reloading task fails if the task list has been regenerated

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#293]
This came up in relation to PR #287 .

After a user edits geometries in a task (via intersection or deduping), the task geometry needs to be refreshed.  If while the user is working on the task the task list is regenerated, the refresh will 404, meaning the task geometry is now stale and not safe to work on.

The UI does not currently handle this case, meaning continues to see stale geometries and can continue to edit.

The most obvious fix is to transition the user to a new task, ideally w/ a helpful UI message.  

Curious if anyone else has feedback.

**Comment by dereklieu** [comment]
👍 could also offer a link that brings the user to that location in the editor, in case they really still want to make an edit.
