### ISSUE TITLE
Add unit tests for non-Macrocosm API functionality

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#298]

**Comment by geohacker** [comment]
@mileswwatkins - is it possible to scribble real quick what the additional API endpoints are? If this is already written down somewhere could you point me to that? Thank you!

**Comment by mileswwatkins** [comment]
@geohacker: Check out the API documentation at the root route. I think these are all the non-core-OSM routes, but you could check any one by comparing against the main Macrocosm repo (https://github.com/developmentseed/macrocosm).

- http://api.openroads-vn.com/#api-Admin
- http://api.openroads-vn.com/#api-Field
- http://api.openroads-vn.com/#api-Field_Data
- http://api.openroads-vn.com/#api-Properties
- http://api.openroads-vn.com/#api-Tasks

**Comment by mileswwatkins** [comment]
But basically all the Macrocosm routes have unit tests against their logic; the new ones largely do not.

**Comment by mileswwatkins** [comment]
@geohacker, this isn't part of the contract, so it can slip into next phase if there's no time in the coming two weeks.
