### ISSUE TITLE
`Raven` not-defined error causes iD visual halting/refreshing

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#30]
<img width="1407" alt="screen shot 2017-07-26 at 11 36 37" src="https://user-images.githubusercontent.com/4959135/28629927-d5a1de30-71f6-11e7-9fec-cd1bc61e1a61.png">

**Comment by maxgrossman** [comment]
For the sake of documenting, the branch I made bug/editor-raven was up to date/conflictless with bug/undefined-raven before bug/undefined-raven was pr'd.

**Comment by maxgrossman** [comment]
..turns out the issue was updating state each time a new hash was added to the url caused the blinking (as doing so re-rendered the page). So, we just stopped state updates from re-rendering the page.
