### ISSUE TITLE
When de-duplicating in Tasks, add interface to pick which road ID to keep

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#310]
When de-duplicating 2+ roads in Tasks, add an interface to handle which ID should be kept:

- If all roads being de-duplicated are either a single ID or a null ID, apply that single road ID to the geometry that's selected as the correct one (no need to prompt user to decide); eg, roads have IDs `123AA12345`, `null`, `null`, and `123AA12345`, user chooses the second geometry, then apply a `current_way_tag` of road ID `123AA12345` to that `current_way`
- If none of the roads being de-duplicated has a road ID, do nothing, and no prompt
- _If the road IDs differ between roads that are being de-duplicated_ (some nulls may be present as well), then prompt the user to pick one of them from a `<select>` or similar. Make it clear if a particular road ID was repeated within the duplication set, and also make it clear which road ID was attached to the geometry that was selected.

**Comment by mileswwatkins** [comment]
@geohacker, for reference, the road ID would be in that way's `current_way_tags`, under the `or_vpromms` key. I believe this is shown in the Tasks view, on-hover of a particular road. @dereklieu is a good point of contact for further questions regarding this ticket.

**Comment by geohacker** [comment]
Thank you for the notes @mileswwatkins! Roughly this is what I think we can do:

* [ ] We'll add the vprommids to a state object called `selectedVprommid` here https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/views/tasks.js#L137 - this will also have "null" incase the ID is null.
* [ ] In the `renderDedupeMode` function, we check if `state.selectedVprommid` > 2 unique and render a `<select>` with all the options with a prompt text.
* [ ] Then on `deleteSuccess` we'll dispatch [`editRoadProperty`](https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/redux/modules/roads.js#L242) with the road_id that the user selected. 

@kamicut thoughts?

**Comment by kamicut** [comment]
I think that 
1. "null" should be labelled as "No vpromm ID" or "Clear vpromm ID"
2. the delete + editRoadProperty should be a separate epic that is conditionally controlled by the fact that you're in "dedupe" mode or not.
