### ISSUE TITLE
map search doesn't handle spaces

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#336]

**Comment by mileswwatkins** [comment]
@jameslaneconkling, can you list steps to replicate?

**Comment by jameslaneconkling** [comment]
On the `/explore` page, type 1+ letters followed by a space followed by more letters into the the search bar above the map.  the space is stripped from the search, e.g. `abc 123` becomes `abc123`.

**Comment by geohacker** [comment]
This is fixed.
