### ISSUE TITLE
VPRoMMS Assets By Province field count is off

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#343]
On `/assets`, field count for Thanh Hoa is 251, but on `assets/401` the count is 248.

The second count is correct, the first is counting deleted roads.

See the `/properties/roads/count` route ([here](https://github.com/orma/openroads-vn-api/blob/develop/routes/road-properties.js#L144-L174)), specifically the join on `current_ways` that checks that the way is visible.

The api endpoints for the `/assets` page use incorrect methods to calculate the field count.  Two thoughts:
* the two endpoints`/admin/roads/total` and `/field/roads/total` could probably be combined (this would also simplify the redux tree on the front end
* the new endpoint should count roads whose ways are visible

**Comment by jameslaneconkling** [comment]
@mileswwatkins the following knex request comes close to producing the correct query:

```javascript
      knex('road_properties as roads')
        .select(knex.raw(`
          SUBSTRING(roads.id, 0, 3) AS province_id,
          SUM((roads.id IS NOT NULL)::int) AS count,
          SUM(ways.visible::int) AS osmcount
        `))
        .leftJoin(knex.raw(`(SELECT way_id, v FROM current_way_tags WHERE k = 'or_vpromms') AS tags`), 'roads.id', 'tags.v')
        .leftJoin(knex.raw(`(SELECT id AS way_id, visible FROM current_ways WHERE visible = true) AS ways`), 'tags.way_id', 'ways.way_id')
        .groupBy('province_id')
```

However it counts ways, not roads, meaning that roads w/ multiple ways are counted more than once.  Take a look at tell me if you have any thoughts.

**Comment by mileswwatkins** [comment]
@jameslaneconkling, I'm not super-proud of this query, but it works!

```sql
SELECT SUBSTRING(rp.id, 0, 3) AS province_id,
    COUNT(DISTINCT rp.id) AS count,
    COUNT(DISTINCT CASE WHEN cw.visible THEN rp.id ELSE NULL END) AS osmcount
FROM road_properties AS rp
LEFT JOIN current_way_tags AS cwt
    ON rp.id = cwt.v AND
    cwt.k = 'or_vpromms'
LEFT JOIN current_ways AS cw
    ON cwt.way_id = cw.id
GROUP BY province_id;
```

**Comment by jameslaneconkling** [comment]
OK, updated the route and removed a redundant route, on [this branch](https://github.com/orma/openroads-vn-api/tree/feature/road-count).  Requires some front end work to update the api call deserialization.  I can give this a little more work tomorrow/next week to get it all sorted.
