### ISSUE TITLE
/properties/roads route sometimes returns duplicate ids

### ISSUE THREAD

**Issue by jameslaneconkling** [orma/openroads-vn-analytics#345]
the following query `/properties/roads?province=21&district=&page=3&sortField=id&sortOrder=desc` returns 

```javascript
[
  { "id":"214YD00061","properties":  {...}, "hasOSMData":false},
  { "id":"214YD00061","properties": {...}, "hasOSMData":false},
  { "id":"214YD00060","properties":{...}, "hasOSMData":true},
  ...
  {"id":"214YD00045","properties":{...},"hasOSMData":true},
  {"id":"214YD00045","properties":{...},"hasOSMData":false},
  ...
]
```

Note: `214YD00061` and `214YD00045` appear twice.  The exact query might not reproduce, given that this was run against a local DB with slightly different data.

My hunch would be that the query returns a road multiple times if the road has multiple ways.  [The query](https://github.com/orma/openroads-vn-api/blob/feature/road-count/routes/road-properties.js#L39-L53) includes a `DISTINCT` clause, but it's possible that's not functioning properly

**Comment by mileswwatkins** [comment]
Great minds! https://github.com/orma/openroads-vn-analytics/issues/344
