### ISSUE TITLE
Allow users in Explore view to visualize properties at different points in time

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#348]
> Ability to use ‘point cloud’ methodology to visualize changes in road attributes over time

Right now, the vector tiles are generated using all properties (eg, IRI) in `point_properties` (https://github.com/orma/openroads-vn-tiler/blob/develop/scripts/conflate-points-lines.js#L16). For this feature, we should create _several tilesets_ of vector tiles, where instead of conflating _all_ `point_property` rows to the `current_ways` geometries, we should only use `point_properties` with a `datetime` of less-than-or-equal-to a given date; this would let us see (known) road quality of the network at that date.

There should also be a `<select>` on the Explore page, to toggle between these tilesets.

Maybe do one tileset per quarter, rather than one per month? Ask the WB team for their preference, but I'd assume we don't want _too_ many time options.

**Comment by geohacker** [comment]
I'd need to understand the usecase a bit more here - there might be another way to just use filters for different tilesets on the client side instead of baking different mbtiles.
