### ISSUE TITLE
Add several context/POI layers to Explore view

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#350]
> Adding 3-5 auxiliary data layers for visualization in Explorer (eg, location of schools, bridges). _Layers must be provided by World Bank by January 19._

Show these additional layers on Explore, with toggles to show or hide each. Probably default to hiding. When I costed this ToR item out, I didn't expect any interactivity, but chew that over with @sarahantos.

**Comment by geohacker** [comment]
Let's keep in mind overall base map design improvements like #370
