### ISSUE TITLE
Create dump of all roads in country, routable

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#351]
This can be used as an input for RAM (https://github.com/orma/openroads-vn-analytics/issues/80), as well as for PCS/RONET.

Check with @Charlesfox1's PCS scripts to determine what the expected format is for the input road data; if this is different from RAM's expected input format, then maybe this Issue will entail creating two different formats of full-country dump.

**Comment by geohacker** [comment]
A network dump is generated daily.
