### ISSUE TITLE
Fix Task allocation

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#371]
See a task in Task, move to Asset/Editor/Explore to check/compare with other information, back to Task to take action but the old task is replaced by a new task.
Can we keep fix the task that currently working on, only introduce new task when user clicks ‘Finish task’ or ‘Skip task’?
A more simple way is open 2 tabs of ORMA in web browser (one for Task, one for others to gather info)

**Comment by geohacker** [comment]
There are two parts to this ticket - we should ticket the separately but for now:

1. Make tasks reliable/consistent/persistent. Related #282 
2. Improve the Task interface to show / browse all road properties

cc @dereklieu

**Comment by geohacker** [comment]
Closing in favour of #282
