### ISSUE TITLE
Add search function in Asset

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#373]
It takes time to jump around many pages in Asset to find a collected VPRoMMS ID.
Can we add search function in Asset or Allow to filter by collected / not collected VPRoMMS ID?

**Comment by geohacker** [comment]
This is missing from our current redesign. Reopening to add it back.

**Comment by geohacker** [comment]
This is done https://github.com/orma/openroads-vn-analytics/pull/482

**Comment by olafveerman** [comment]
Feedback:

AN:
Assess Page: Inconsistent of Admin unit name
•	Mixed use of EN and VI: TCan Tho, Bỉm Son Town
•	Shortened Province name: 
o	TP - T
o	Ho Chi Minh - Ho Chi M

AN:
Search result window is not automatically dismissed after a result selected (as in the Editor Page) – blocking the part of interface including the download and add asset tool

DBC
My comment is the same as filter function. #402 

cc @geohacker

**Comment by geohacker** [comment]
> Assess Page: Inconsistent of Admin unit name

Admin unit name should be now fixed after importing correct admin layer data.

> Search result window is not automatically dismissed after a result selected (as in the Editor Page) – blocking the part of interface including the download and add asset tool

This is a bug. We will open a separate ticket to track this.
