### ISSUE TITLE
Compare VPRoMMS ID

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#374]
- Allow to choose and show multiple VPRoMMS ID?
- OR add label to roads in Explore?
![3](https://user-images.githubusercontent.com/31137016/35429604-a87987ee-026c-11e8-9441-cb6175658b1b.jpg)

**Comment by geohacker** [comment]
We should certainly consider adding labels on the map. A compare interface is probably not on the cards right now.
