### ISSUE TITLE
Completely delete a VPRoMMS ID and all data attached to it

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#376]
To assign new route and properties for an existing VPRoMMS ID:
Delete a VPRoMMS ID, then create a new VPRoMMS ID that has the same ID with the previous one to upload new data to it. But all data of old VPRoMMS ID are recovered. It seems old VPRoMMS ID data was not deleted.

**Comment by geohacker** [comment]
This sounds like a regression to me.

@PCDuc - can you give an example VPRoMMS ID that you tried deleting and creating a fresh road for? Thank you

**Comment by PCDuc** [comment]
You may try to delete any VPRoMMS ID then create a new one with the same ID. All the properties will be restored, meanwhile we want to assign new properties to the ID.
