### ISSUE TITLE
Select properties from an existing list in 'Create new property' function

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#377]
‘Create new property’ function allow user to type in any property name. To keep the consistency between VPRoMMS IDs, we should only allow to select properties from an existing list.
![5](https://user-images.githubusercontent.com/31137016/35430014-5e2ec972-026e-11e8-8eb8-ecf843925593.jpg)

**Comment by geohacker** [comment]
This is a good idea to make adding new properties faster. Should we continue to allow the users add arbitrary properties?

**Comment by PCDuc** [comment]
I think the best case is allowing users to update the list. Otherwise, add arbitrary properties will create a mess.
