### ISSUE TITLE
Allow to edit an existing property value and save it

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#378]
![6](https://user-images.githubusercontent.com/31137016/35430090-a981b510-026e-11e8-8bd7-2cd7e6698020.jpg)

**Comment by geohacker** [comment]
This is already possible in the new release:
![image](https://user-images.githubusercontent.com/371666/35452987-8cb6838e-0296-11e8-96b5-71a27edd5891.png)


@PCDuc - please reopen if you think this isn't working as expected!
