### ISSUE TITLE
Show length and highlight new VPRoMMS IDs.

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#380]
For newly created VPRoMMS ID, the lengths is not shown, and there is no highlight in explore

![7](https://user-images.githubusercontent.com/31137016/35430240-5120871a-026f-11e8-8bbf-788708378c8e.jpg)

**Comment by geohacker** [comment]
Thank you for the ticket @PCDuc. I'm not 100% sure what exactly you're referring to in the above issue. Does the VPRoMM have a geometry? Could you link me to it?

**Comment by PCDuc** [comment]
@geohacker As you can see in the above image, I created new VPRoMMS ID '213YD00002' and uploaded its geometry + properties. However, its length is not shown in the data area. Moreover, when you click on "View", the VPRoMMS is not highlighted on the map as other VPRoMMS IDs. My guess is all newly created VPRoMMS IDs will go to another dataset?

**Comment by geohacker** [comment]
Will be fixed in #409
