### ISSUE TITLE
Asset

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#385]
IN Assets the "View" button doesn't make a lot of sense. we should make it be "edit' rather than view, as the Explore tab is essential a viewing function.  can we have a link from the assets to the editor?

I think it's important have the option of imagery when looking at an individual asset - By allow people to click through to editor - we will accomplish this.

**Comment by geohacker** [comment]
Changing the name is easy. 
Editor link is a little tricky.

**Comment by geohacker** [comment]
Will be covered by #409
