### ISSUE TITLE
Persist map state, task ID, and editor map state in the URL

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#394]
Zoom level not retained when moving between Explore and Editor tabs on Google Chrome

**Comment by geohacker** [comment]
We'll have redo how URL persistence happens across the app. This is a bit of work and touches all the modules.

**Comment by geohacker** [comment]
This is fixed:

1. From the asset page one can now go to the editor to the area where the edit needs to be made
2. From the explore page one can click the geometry to see the asset page. 

cc @olafveerman
