### ISSUE TITLE
Editor - color of national roads

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#398]
IN Explorer the national roads are Black, but in Editor they are Yellow - we need to pick a color that stands out and stick with it throughout the system.

**Comment by sarahantos** [comment]
@geohacker I see that you have made the roads dashed so they dont appear the same as the national roads. However if thats the styling we go with the legend now needs to reflect this change.

**Comment by geohacker** [comment]
@sarahantos no the dashed roads are roads without no vprommid, in the Explore page, as discussed in this ticket https://github.com/orma/openroads-vn-analytics/issues/389#issuecomment-363745578. I've also added a basic legend to make this clear 

![image](https://user-images.githubusercontent.com/371666/36186616-25b99fb6-1166-11e8-8a07-64eb84d7d493.png)

**Comment by geohacker** [comment]
We'll redesign the map style overall in the upcoming phase to keep them consistent across views.
