### ISSUE TITLE
Make the missing-property roads gray, instead of black

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#40]
Right now, roads that are missing a property (including those that have no VProMMS, and thus no properties) are shown as black. Black is MapboxGL's default color for showing missing-data roads. You can't use `null` as a key in the `line-color`'s `stops` array, which would've allowed us to solve this simply.

**Comment by geohacker** [comment]
More basemap adjustments #370

**Comment by geohacker** [comment]
This is a duplicated of https://github.com/orma/openroads-vn-analytics/issues/389 - we decided to use dashed roads for representing non VPROMM roads. The alternative would be to create another dataset that makes non vpromm and non iri exclusive but that's really hard to do.
