### ISSUE TITLE
Improve tasks instructions panel

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#400]
It is often unclear what the tasks pane wants me to do. Take these two roads: 
 
![image](https://user-images.githubusercontent.com/22750546/35756339-e7eaaca6-0838-11e8-9dc3-401305e6a8b4.png)

As a user, what do you want me to do here? I have selected my roads – but there are no labels to indicate that they are the same VPROMMS ID, so I don’t know whether to remove duplicates. Further, it looks like there is a missing intersection here, but that option is greyed out. Thus – I don’t understand what to do in this task. I think this pane could benefit from a ‘I expect you to do X to these two roads’ rather than just listing the remaining tasks, and expecting me to guess what to do with the input roads.

**Comment by geohacker** [comment]
We should add more instructions on this page. 

@sarahantos - just to clarify the above scenario. Clicking on 'Remove Duplicates' enters the deduplication mode. The next step there is to pick the road that you'd like to keep. The system automatically will prompt for selecting VPROMMID if it's necessary - if they differ.

**Comment by geohacker** [comment]
Task instruction panel is now fully revamped and focuses on each step individually.
