### ISSUE TITLE
Task - remove duplicates bug?

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#403]
The suggestion list in “Remove Duplicates” is not working correctly (more suggestions than actual showing?). And the list should be available right after click on “Remove Duplicates”.

**Comment by geohacker** [comment]
@sarahantos could you give an example task? I'm running through a few different cases of mixed vprommids and same vprommids and they all same to logically follow the steps for me.

**Comment by geohacker** [comment]
Fixed in https://github.com/orma/openroads-vn-analytics/pull/421
