### ISSUE TITLE
Tasks - deduping suggestion

### ISSUE THREAD

**Issue by sarahantos** [orma/openroads-vn-analytics#404]
When detected duplicate roads, automatically apply the rule of keeping a road with higher management class and report the list of deleted duplicates? This will help to reduce the number of task.

**Comment by geohacker** [comment]
I'm not sure if this is good technique. It depends on the task confidence really. @dereklieu would you know?

**Comment by dereklieu** [comment]
I'm not too familiar with the management class concept, but if it's something that an operator applies, it seems that a duplicate road that's automatically ingested would run the risk of being removed even if it contained a better geometry than what's currently in the system.
