### ISSUE TITLE
Assets - redesign VPROMM page

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#409]
The View button in the VPROMM table leads to a page about that particular road. Currently, this page only contains a map that shows the different traces associated to the VPROMM id. Discussing with @sarahantos and @geohacker, we could build out this page and consolidate all VPROMM information. At this stage, this would involve:

- moving the properties from the VPROMM table to this page. This makes them easier to read and to edit
- clarify that the current map contains the different traces for the VPROMM

This would also address some of the usability issues reported with the VPROMM table:

![image](https://user-images.githubusercontent.com/751330/35921813-c0a134da-0be9-11e8-9e9e-244e53e41156.png)

**Comment by geohacker** [comment]
We redesigned the asset page.

**Comment by geohacker** [comment]
Per chat with Vietnam team, sharing the Asset page wireframes again, this time on this ticket:

## Assets overview page
<img width="1440" alt="assets--overview 2x" src="https://user-images.githubusercontent.com/371666/46545463-18dc7580-c8e4-11e8-855a-986833c00beb.png">

## Assets province page
<img width="1440" alt="assets--province 2x" src="https://user-images.githubusercontent.com/371666/46545472-1c6ffc80-c8e4-11e8-8022-bdc493b652ec.png">

## Assets district page
<img width="1440" alt="assets--district 2x" src="https://user-images.githubusercontent.com/371666/46545478-209c1a00-c8e4-11e8-825a-6f2bc7889071.png">

## Single Asset page
<img width="1440" alt="assets--single-overlays 2x" src="https://user-images.githubusercontent.com/371666/46545493-285bbe80-c8e4-11e8-8b4e-1394c0dc6bea.png">

As discussed previously with Kai and Sarah on July 25. The feedback we received are along the lines of expanding statistics that's displayed on each of the page. These are outlined here https://github.com/orma/openroads-vn-analytics/issues/438

The single asset page is already functional, for example: http://openroads-vn.com/#/en/assets/road/313AL00001/

**Comment by kai2ser** [comment]
This tread refers to Section 3.2 documentation of the ORMA Instruction/Operations Manual as per https://docs.google.com/document/d/19oKGGrV12zwqZEr3woqTCNunwsSVCDlzvgVj-IUj4VA/edit

Welcome the communication on de facto functionality as experience but the user, and explained to team since the to serve as "trainer of trainers."

**Comment by kai2ser** [comment]
In terms of the workflow around asset management, the documentation should clarify:

i) how are key state attributes as per Table 4 displayed if they they vary at the sub-section (ProMMS ID level). So for example IRI varies by section, but it is summarized for RM-CBA (Section 4 of manual) at section level for export
ii) If the later addition of a section overlaps with a previously done section, does this revert back to "to fix workflow"

**Comment by kai2ser** [comment]
The key point is that we really need to check that the workflow from capture-->management-->application for RM-CBA has all key steps.  This has really been the plea previously for a few more interactive presentations to the wider Vietnam (beyond Duc previously with GOST)

**Comment by geohacker** [comment]
@kai2ser to answer the questions on workflow:

> i) how are key state attributes as per Table 4 displayed if they they vary at the sub-section (ProMMS ID level). So for example IRI varies by section, but it is summarized for RM-CBA (Section 4 of manual) at section level for export

At a subsection level, each IRI measures are represented as absolute values at specific locations. For sections, these are aggregated. Subsection attributes from RLP that are imported are stored as points and then associated to sections and roads as necessary during export and analysis.

> ii) If the later addition of a section overlaps with a previously done section, does this revert back to "to fix workflow"

This is related to conflation. If a later added section overlaps 60% or more points with an existing section, we do not import geometry, but add attributes and make sure the assigned VPROMM ID is consistent. We would love if the Vietnam team can do a thorough testing. More about this here https://github.com/orma/openroads-vn-analytics/issues/436

**Comment by kai2ser** [comment]
1. Thanks. So to confirm that this is now implemented for all the core features in Table 4, which are needed for RM-CBA, including surface type, and not just IRI?  Can you screen post an example of this?

2. When a section which is fixed to the "static" section definition is exported, but may vary by segments, do we have a "homogenization filter" for import into RM-CBA or any other model. So let's say a road is 90% by length os segments paved, and 10 dirt, where do we run the translation that at least for the legacy RM-CBA that "record" is translated to say all paved (since the RM-CBA model takes only one state attribute, as it assumes its homogeneous).

3. For future reference will the documentation provide framework to other programmers to write simple import scripts.  So for example the RouteShoot CVS files tag videos by sections.  Which part of the documentation is this provided.  We just want to make sure the import function can be expanded later, and is not hardwired for RLP 1/2

4. Sounds good on testing. If you and Duc now good on the reference geometry, we can test

**Comment by geohacker** [comment]
> 1. So to confirm that this is now implemented for all the core features in Table 4, which are needed for RM-CBA, including surface type, and not just IRI? Can you screen post an example of this?

On the single Asset view, the values that are imported to ORMA which can be aggregated will be shown as below: 

![orma-asset-page](https://user-images.githubusercontent.com/371666/46666832-5f341c00-cbe5-11e8-92ae-5a35a91bf838.png)

> 2. When a section which is fixed to the "static" section definition is exported, but may vary by segments, do we have a "homogenization filter" for import into RM-CBA or any other model. So let's say a road is 90% by length os segments paved, and 10 dirt, where do we run the translation that at least for the legacy RM-CBA that "record" is translated to say all paved (since the RM-CBA model takes only one state attribute, as it assumes its homogeneous).

I think we still need to do a full round of ORMA -> CBA testing with real data, but to answer the question - each export from ORMA is associated with one export of geometries that are identified by vpromm id, section id along with a timestamp. These sections will be homogenous. The only way to extract segments is to look for points within a section, which will be part of the geometry export. 

> 3. For future reference will the documentation provide framework to other programmers to write simple import scripts. So for example the RouteShoot CVS files tag videos by sections. 

Yes of course. RLP imports are very specific to the RLP style CSV files and hence RouteShoot integration cannot use the same API. But it is extensible. The RLP data is translated to OSM data schema which will remain consistent. Any change to the data on ORMA will create an [OSM changeset](https://wiki.openstreetmap.org/wiki/Changeset). This is also captured in the detailed API documentation http://api.openroads-vn.com/

**Comment by PCDuc** [comment]
Beside the comment from Kai and co Dang, here are my comments on the design of Asset page above:
1. On the "Asset overview page": could you explain what is the meaning of "Field" column? Why in some cases, the value is bigger than total
2. On "Assets province page" and "Assets district page": The table represent assets at road level (VPRoMMS ID) however some of the attributes varies at Section level such as Type, Width, Grade. The asset attributes need to go with different asset levels. Please refer to VPRoMMS Architecture.
3. On "Single Asset page": As same as above, attributes from Link and Section level are showed at Road level lead to confusion. It needs to have separate visualization for each levels under a road ID.

**Comment by geohacker** [comment]
@PCDuc:

> 1. On the "Asset overview page": could you explain what is the meaning of "Field" column? Why in some cases, the value is bigger than total

Field indicates number of Assets with field data

> On "Assets province page" and "Assets district page": The table represent assets at road level (VPRoMMS ID) however some of the attributes varies at Section level such as Type, Width, Grade. The asset attributes need to go with different asset levels. Please refer to VPRoMMS Architecture.

These are aggregated at the Asset level for visualisation. I've opened a separate ticket capturing the request of section level needs on the Asset page #481. 

> On "Single Asset page": As same as above, attributes from Link and Section level are showed at Road level lead to confusion. It needs to have separate visualization for each levels under a road ID.

We can certainly remove attributes on the Asset page that doesn't need to be shown at the Road level. Could you point them out here? Thank you.

**Comment by olafveerman** [comment]
Feedback provided by the team:

DT: ORMA 3.0 still provides confusing road attributes (check for Asset/Edit of each road section). WB team provided the road attributes in group.

AN: Assess Page/ Road length: GPROMMS LENGTH is taken from MTEF table – I guess – But How the value for WON LENGTH come from? Could you explain?

DBC: Regarding the sorting, instead of by VPROMM ID, there should be other criteria like IRI, type…

cc @geohacker

**Comment by geohacker** [comment]
> DT: ORMA 3.0 still provides confusing road attributes (check for Asset/Edit of each road section). WB team provided the road attributes in group.

The Asset page will start showing only asset level properties after the import is complete. Section request is captured separately here #481. 

>  But How the value for WON LENGTH come from? Could you explain?

Both GPROMM and WON lengths are also calculated within ORMA to show the progress of completion. This is updated every day. 

> DBC: Regarding the sorting, instead of by VPROMM ID, there should be other criteria like IRI, type…

This is a new feature request. Happy to open a different issue to outline the effort if needed.

**Comment by geohacker** [comment]
![image](https://user-images.githubusercontent.com/371666/48777793-8eb46900-ecf9-11e8-8db2-500697f8fc4f.png)

Sections view is now available.
