### ISSUE TITLE
Number of collected VPRoMMS IDs don't sum up correctly

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#419]
@geohacker  Take the case of Yen Dinh, Thanh Hoa for instance.

The top bar show 92% (115/125) completed but the below data only shows 2 VPRoMMS IDs are missing (not highlighted): 213YD00005 and 214YD00081.
In additional, 213YD00005 has all its data (length + IRI) but still be counted as missing? I'm not sure why this happens.
![image](https://user-images.githubusercontent.com/31137016/36769820-5ac392f2-1c79-11e8-93de-0ce71fe87740.png)
![image](https://user-images.githubusercontent.com/31137016/36769798-293f31fa-1c79-11e8-8bb7-96924995f122.png)

**Comment by geohacker** [comment]
This was fixed as part of the redesign, and along with new statistics. This needs a bit more testing after the data imports.
