### ISSUE TITLE
Tasks: workflow redesign

### ISSUE THREAD

**Issue by ricardomestre** [orma/openroads-vn-analytics#433]
Related to #423

In an effort to make the Tasks workflow more clear, we propose a redesign:

Some notes:

- Workflow is now presented in a multi-step format
- In addition to the map, roads appear also listed in the overlay panel
- The user is asked to pick an action first; this will determine what is possible to do in subsequent steps

---

<img width="1440" alt="tasks__solve 2x" src="https://user-images.githubusercontent.com/1016701/42518539-f405c122-8459-11e8-8dad-24d499b9e4ec.png">

---

<img width="1440" alt="tasks__solve--duplicates-flow 2x" src="https://user-images.githubusercontent.com/1016701/42518536-f3c55f24-8459-11e8-9f7e-6bdafc7c7525.png">

---

<img width="1440" alt="tasks__solve--intersection-flow 2x" src="https://user-images.githubusercontent.com/1016701/42518537-f3e74486-8459-11e8-9329-22362f851ed2.png">

---

CC/ @dereklieu @geohacker @sarahantos @PCDuc

**Comment by geohacker** [comment]
We shipped this with the help of @ricardomestre @batpad and @danielfdsilva! 🌮
