### ISSUE TITLE
Process for WON (shp) to OSM

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#435]
Part of #426. We'll use shp2osm.

**Comment by geohacker** [comment]
@batpad here's roughly what I think we should do:

* write a script to take a shp file and convert to osm using shp2osm. or ogr2osm.
* then we could most likely use the macrocosm import through osmosis https://github.com/developmentseed/macrocosm#importing-data

**Comment by batpad** [comment]
@geohacker this is what I was able to do to import the data into the `macrocosm` db:

Use `ogr2osm` to convert the shp file to a `.osm` file, something like:

    python ogr2osm.py -o /tmp/output.osm ~/path/to/shpfiles/won.shp

Use `osmconvert` to add fake author attributes to the xml to be compatible with v0.6 of the OSM API:

    osmconvert test.osm --fake-author -o=tmp/test-0.6.osm

Use `osmosis` to import the osm file into the db, something like:

    ./bin/osmosis --read-xml file=~/seed/openroads-vn-api/tmp/test-0.6.osm --write-apidb host="127.0.0.1:5433" validateSchemaVersion="no" database="openroads" user="postgres" password="postgres"

The ways look to be imported okay in the `current_ways` table. There were a few attributes in the shape file that I'm not sure if we need, stuff like `RoadType`, `RoadWidth`, `RoadLength`, `RoadClass`, and most of the values seem to be empty. Not sure if we want to keep these or strip them out.

But the basic import seems to work - we can discuss how best to package this up into a single script or so.

**Comment by olafveerman** [comment]
The [`openroads-data`](https://github.com/orma/openroads-data) repo contains a lot of information about the import processes we did for ORMA Philippines.

In that project we used `ogr2osm` with the `add-author` flag to set the author. We also added an option to ogr2osm to generate a proper changeset, allowing us to import it using the API without having to use `osmosis`.

**Comment by geohacker** [comment]
@batpad this is amazing! I think it'll be good to keep those when they have values - it's possible that most geometries will have no attributes. 

We can add this as a helper script that allows imports - these shapefiles can get pretty big and it's a onetime operation so we don't have to make it part of the API.

**Comment by batpad** [comment]
@olafveerman :+1: -- I was missing the `add-author` flag in ogr2osm - this should eliminate the need for `osmconvert`, and it will be useful to look at the Translation files if we need to do any processing on the tags - I was  wondering as well if a better approach is to create changesets and then use the API to upload, or just use `osmosis` connected to the db. I think the rationale for using `osmosis` here was that these files can get really big and then it's nice and fast to be able to use `osmosis`. @geohacker, thoughts?

**Comment by batpad** [comment]
So importing subsequent files via `osmosis` does not work unless we manually tweak the `id`s defined in the XML.

I think it makes sense to explore the changeset approach and let the `macrocosm` API handle things like assigning IDs to objects.

**Comment by batpad** [comment]
Just to document what worked well to create changeset files - clone https://github.com/orma/openroads-data and run similar to the example given in the [README](https://github.com/orma/openroads-data/blob/develop/readme.md):

    python bin/ogr2osm/ogr2osm.py path/to/data/road.shp --add-user="openroads" --create-changeset

You might need to add a custom `translation` similar to the examples in the `openroads-data` repository to translate the attributes in the shape-files to tags that make sense in our schema.

**Comment by geohacker** [comment]
@batpad thank you for outlining the work so far. I think what we could do is create a changeset using ogr2osm and then use osmosis to upload the [change to the db](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.46#--write-apidb-change_.28--wdc.29)

**Comment by batpad** [comment]
@geohacker I think we may be better off just using the macrocosm API to upload via a POST request or so with the changeset. The reason being that ensures that the elements being uploaded get unique ids. The API layer handles assigning proper ids if the incoming ids are set to a negative value (which is what we'll get with the changeset generated with `ogr2osm` - if we use osmosis to populate the db directly, we will probably get bad ids in the system.

**Comment by geohacker** [comment]
This is done https://github.com/orma/openroads-vn-api/pull/111
