### ISSUE TITLE
Refactor RLP imports

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#436]
Part of #426:

During an RLP import:
* we look at the point where a VPROMM starts, infer the section from the VPROMM spreadsheet, create a way at this distance, attach attributes like IRI, pavement type from RLP and store this. The start and end of the way will be nodes.
* for every subsequent data collection from RLP for this VPROMM we can use a binary decision making to keep the existing way or replace entirely by overwriting the attributes.
* each way will be a section with homogenous attributes.
* each way will have an attribute vpromm_id and id. vpromm_id+id will be the section id of the vpromm.

**Comment by geohacker** [comment]
Since we are now supporting WON, our RLP imports need to respect possibility of existing geometries, and add new ones as necessary - as outlined above. I'll try to break this into approaches we can implement now:

### 1. Client-side independence

At the moment, RLP geometry and properties uploads are client side waiting. We should change this and make the imports like jobs that eventually complete on the backend. The following conflation will be expensive operations and it's not ideal to have the front-end wait for them to complete. @batpad what do you think is the best way to deal with this?  We'll need some way to see existing uploads and progress perhaps?

### 2. Find if WON has the geometry.

To find if we've road geometry along the RLP points, we'll have to query the `current_nodes` table for nodes that are close and part of a way. If at least 50% of points have a matching node (50% is a bit arbitrary), then we can consider that there's a geometry that exists. 

### 3. No geometry

If there's no existing geometry, we've to prepare the road geometry like exactly like how RLP is preparing now - stitch all the points together to create a way. One additional step we've to do is attaching this new way to the existing road network. For this:

1. find the start node of the new road
2. query for the closest node in the current_nodes table.
3. in the new changeset, replace the first node with the closest node from current_nodes. 

This doesn't take into account the direction and hence is probably a bad idea. The alternative is to not do the conflation and let this intersection problem surface in the tasks. We can probably start with this approach @batpad.


### 4. Conflation - existing geometry.

If the road geometry exists in WON, we've to query for the way id, and fill all the point properties with this id. Basically the attribute part of the existing RLP conflation. There are couple of scenarios here to judge if we should replace the attributes or not, but to begin with we should replace the attributes assuming that RLP will always have better resolution. 

There's also a possibility that the RLP geometry might be better than the WON. I'm not sure what signals to look for at the moment, but I think we could also completely replace the geometry.

**Comment by batpad** [comment]
>  The following conflation will be expensive operations and it's not ideal to have the front-end wait for them to complete. @batpad what do you think is the best way to deal with this? We'll need some way to see existing uploads and progress perhaps?

Some research into this points to `Kue.js` as possibly a good fit: https://github.com/Automattic/kue . This will run as a separate process, and use Redis as the message broker. So, in the Webserver, we would create a `job` and send it to Redis, which will be picked up by `Kue`. And there are all sorts of callbacks to monitor progress, handle errors, etc.

This does add a dependency on Redis, but this seems reasonable - I don't see a reasonable way around it do  this kind of deferred processing.

Kue seems fairly reasonable to setup and try out. If it seems like a reasonable approach, I can create the scaffolding and test that the delayed job functionality all works as one would expect.

Another library I looked at was `Bull`: https://github.com/OptimalBits/bull - that seems to run in the same process as the webserver - it seems pretty similar, and I don't have a strong preference for either, Kue seemed some-how a little bit nicer / simpler.

**Comment by geohacker** [comment]
We just shipped basic conflation as outlined above.

**Comment by geohacker** [comment]
We've to look at attribute conflation again - particularly this case:

If WON has a geometry/geometries that are overlapping the RLP geometry, we want to attach the VPROMM ID to all these WON ways using the or_vpromm tag. 

cc @batpad

**Comment by geohacker** [comment]
This is done in the above PR!
