### ISSUE TITLE
States for sections and vpromms.

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#439]
@PCDuc mentioned that we should have states for sections and vpromss. 

* status - pending: review of geometry and attributes pending
* status - reviewed: someone reviewed but not complete
* status - complete: someone reviewed and marked as complete. so no more edits.

Need more details on how this should work.

**Comment by geohacker** [comment]
State apply for VPROMMS and not sections. Here's how states should work:

* while importing vpromms table, all assets get state `pending`
* we need a flag to identify if a vpromm has a geometry or not. could perhaps just add a state called `geometry`
* when someone reviews the vpromm from the asset page (cc @ricardomestre), they can switch the state to `reviewed` manually. 
* once in reviewed state, the geometry and attributes are not modifiable unless the user switches the state to `pending`
* in the asset page, we want to show stats about vpromms that are pending and reviewed. cc @ricardomestre. to keep track of review progress.
* if an asset has one or more tasks that are related to it, then the user cannot move it to review state until those are fixed. 

cc @batpad

**Comment by danielfdsilva** [comment]
The state should be present on the `/properties/roads/{vpromm}` response and there should be an endpoint to update it.

**Comment by geohacker** [comment]
States are implemented now.
