### ISSUE TITLE
Include province and district in road/properties response

### ISSUE THREAD

**Issue by danielfdsilva** [orma/openroads-vn-analytics#442]
To display the district and province a road belongs to, this information should be in the api response.

**Comment by geohacker** [comment]
Sounds good. I think the best way to do this is:

* add the district and province short codes to the database `admin_boundaries` table using this list https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/constants.js as the reference.
* query the table and return it with this endpoint https://github.com/orma/openroads-vn-api/blob/9275d32ebc46bf780b2e8d5c6974e0551fea8622/routes/road-properties.js#L80

**Comment by geohacker** [comment]
Done.
