### ISSUE TITLE
Tasks: add last updated timestamp

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#444]
For our new tasks workflow we want to show when tasks were updated last on the front-end. Here're the steps involved:

* api: add a new column in the tasks table in the api via a migration like https://github.com/orma/openroads-vn-api/blob/master/db/sql/201801151858_tasks_province_id.sql
* tiler: find the timestamp and add it in the csv in the tiler https://github.com/orma/openroads-vn-tiler/blob/master/scripts/generate-tasks.sh#L27
* tiler: insert to timestamp column during task update in the tiler here https://github.com/orma/openroads-vn-tiler/blob/master/scripts/generate-tasks.sh#L30 in 
* api: expose this in the nexttask api call.

cc @batpad @dereklieu @ricardomestre @danielfdsilva

**Comment by batpad** [comment]
@geohacker PR here: https://github.com/orma/openroads-vn-api/pull/112 - I side-stepped adding the current timestamp explicitly during CSV generation in the tiler by adding a default value of `now()` to the column - let me know if this approach works. If yes, this should be all we need for this feature on the API - I will work on integrating the front-end.

**Comment by geohacker** [comment]
This is done!
