### ISSUE TITLE
Nav bar buttons don't highlight for sub-pages

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#47]
For example, when you first navigate to Analytics, the nav bar button looks like:

<img width="258" alt="screen shot 2017-07-27 at 22 20 58" src="https://user-images.githubusercontent.com/4959135/28699815-e1e35c86-7319-11e7-8b05-7c48f7d3ab84.png">

But once you navigate to a single-province analytics page, Analytics is no longer highlighted in the nav bar:

<img width="175" alt="screen shot 2017-07-27 at 22 21 34" src="https://user-images.githubusercontent.com/4959135/28699836-f6add3ee-7319-11e7-8ade-461bf421960c.png">

Similar thing happens when you navigate to Editor (it's highlit), but then when you move around inside Editor and it adds a `/map=6.00/108.519/14.101` to the end of the endpoint, the nav bar highlight disappears.

**Comment by maxgrossman** [comment]
handled with #55. will test in develop before closing.

**Comment by maxgrossman** [comment]
indeed fixed with #55
