### ISSUE TITLE
Feature to browse and visualise sections on the Asset page

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#481]
Documenting comments from Dang in the [workflow document](https://docs.google.com/document/d/19oKGGrV12zwqZEr3woqTCNunwsSVCDlzvgVj-IUj4VA/edit?ts=5bbc6c36) about browsing section/link attributes and visualising the geometries. This is also a request raised by @PCDuc. This is a core feature.

> Editing attributes will be done from Segment – Section – Link - Road corresponding to the structure components and cover data as in the Roads Table/ Links Table/ Sections Tables/ Segment Tables as above.

Editing attributes and geometry for Section and Link are available through the editor. This is to make sure the geometry and attributes are edited together with full context. 

> 4 options for editing follows structure components of Road/Link/Section/Segment. Each component could includes one or more than one pages with similarity of current format of the interface page is similar, but attributes need be located in right group and order. For example with Section, 03 pages of admin data/ pavement characteristics/ traffic could be needed . Each page cover data as in the Admin data table/ Pavement characteristic table/ Traffic Condition table (in part of Road data in ORMA architecture)

At the moment the Asset page only supports Road level attribute view as well as Road level attribute editing. To add a list of Sections/Links and also display the attributes on the page involves a fair bit of development time:

* Add an API end point for fetching all sections and links per Asset
* Add interaction to visualisation of change the list of attributes
* Redesign the single Asset page layout to accommodate a list along with aggregated attributes

cc @olafveerman @kai2ser @PCDuc @batpad

**Comment by olafveerman** [comment]
We propose to add a tab to the asset page that shows all sections of the VPROMM and their core attributes. This allows the user to quickly compare attributes of the granular sections, with the higher level attributes imported from the VPROMM table.

![rect9](https://user-images.githubusercontent.com/751330/47857910-386e9d00-ddc1-11e8-9ae9-1c7b2ff7ed19.png)

Notes:

* when a user hovers over a row in the table, the corresponding section will be highlighted on the map.
* CVTS information will be integrated in the section table. This colum shows the average daily traffic as calculated from the CVTS dataset. If no CVTS data was registered on the section, we will mark it as `n/a`.

**Comment by olafveerman** [comment]
Feedback received from the team about these wireframes:

> Current design of data structure in ORMA required users to input Section attribute manually through Editor. However, this is a very labor intensive task while Section attribute data is already available in Excel file. ORMA should allow to upload these Section attribute tables and link to recorded geometries using VPRoMMS ID, Link number and Section number.

**Comment by olafveerman** [comment]
Thanks for your feedback to the integration of section information on the dashboard. We will proceed with the implementation of this interface, and you can expect it to be included in a release early next week, around November 7. From that moment on. any sections that are associated to a VPROMM will appear on its corresponding page.

Regarding your request to have an automatic process to import section level information into the ORMA database, we consider this to be a separate request, for which we will open a ticket.

**Comment by geohacker** [comment]
Fixed in https://github.com/orma/openroads-vn-analytics/pull/513
