### ISSUE TITLE
Download button gives error message

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#491]
![image](https://user-images.githubusercontent.com/31137016/47144856-9778e000-d2f2-11e8-9469-b4d8f7d50568.png)

**Comment by geohacker** [comment]
@PCDuc thank you for the ticket. This looks like a bug, the provincial exports aren't working right now. We will fix this shortly. Thank you for noticing!

**Comment by geohacker** [comment]
Fixed in https://github.com/orma/openroads-vn-tiler/pull/56

@PCDuc - The provincial dumps are back and updated every 24 hours.
