### ISSUE TITLE
Error from administrative boundary list

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#492]
- There are more provinces than only 14 in the previous list but some provinces are split into two lists (such as Bac Ninh, Ha Giang, Quang Binh) or have typos in the name (such as Ba Ria-Vung..., THo Chi M..., ...). Some districts name also have typos.
- Some provinces don't have any districts (because of the split above) or missing districts. The above error and this error may come from admin layer.

**Comment by geohacker** [comment]
@PCDuc thank you for the ticket. You're right, this error comes from the admin boundary layer that we are using on ORMA, as well as the province and district code mapping we're using. 

I'm looking at the admin file the Vietnam team shared with us and it does have a lot of problems like the one below:

![image](https://user-images.githubusercontent.com/371666/47152860-82547f00-d2fb-11e8-9846-877ff79becbc.png)

_The inner ring polygon for Bac Ninh makes ORMA think that they are two different provinces. Hence the missing districts, and mismatch in VPROMM list._

The best way is if you can help us by giving us a cleaned admin layer with the following:
1. Required provinces, name in en and vn, vpromm code and polygon
2. Required districts, their parent province id, name in en and vn, vpromm code, and polygon

Also a note that we should clean up the admin layer issues before uploading new vpromm data or WON (#473) as this will cause more errors.  

cc @kai2ser @olafveerman @batpad

**Comment by PCDuc** [comment]
Hi @geohacker 
Please find the 2016 cleaned administrative layer in the following shared folder:
https://1drv.ms/f/s!AlXoorZjtVf-3za8tKwS1Wfng2iN

**Comment by geohacker** [comment]
@PCDuc thank you for this. I see that you've added the code for provinces but we also need the code for districts. Could you add them and share the new file please? Thank you!

Also, if we want to show only the 14 provinces, could you list them here? We can then filter just these on the Asset page.

**Comment by geohacker** [comment]
@PCDuc I'm blocked by not having the district codes. Any chance you can share this today? We're not able to do any data imports until we fix this. Thank you!

**Comment by PCDuc** [comment]
Sorry, I'm fully occupied today. Is the district code that you need, in text code, such as YD, TT, CT,...? If that the case, could you look for it in ORMA database, since I ran through it with Miles sometimes ago. Otherwise, I will need to check again and can only share to you by tomorrow.

**Comment by PCDuc** [comment]
@geohacker Not the admin layer, I mean there was a separate table of matching district code between integer and text. Basically, the text code is 2 digits and combining of first letter of each word in district name, with some exceptions. I will come back to this tomorrow.

**Comment by geohacker** [comment]
@PCDuc I'm afraid that list also has errors which is how ultimately the database got these errors. I think you have a better idea of how to match these and that will be really helpful. Thank you!

**Comment by geohacker** [comment]
@PCDuc 👋 do you have a new districts shapefile with the codes? Thank you!

**Comment by PCDuc** [comment]
@geohacker 
I've uploaded new shapefile with district code together with an excel of coding and some notes to the shared folder: https://1drv.ms/f/s!AlXoorZjtVf-3za8tKwS1Wfng2iN
Please see the note and come back to me if it's not clear to you. Thanks!

**Comment by PCDuc** [comment]
@geohacker Never mind that note column, you can delete that in the shapefile

**Comment by geohacker** [comment]
I see your notes in the excel file, but I don't think I follow:

* Third digit code is 2: Provincial road (don't use ORMA_DisCode), put in a separate group
* Third digit code is 3 or 4: Use ORMA_DisCode to identify district
* Some VPRoMMS ID are incorrect (not follow the structure, not enough number of digits): Use previous auto correct VPRoMMS tool

**Comment by geohacker** [comment]
Duc explained the above notes to me on Slack:

> If Management class is 2 which is provincial road, which mean it will go through many district, you can't put it into a district list but need a separate group, says Provincial roads
> Also, if Management class is 2, and you group them into a separate list, you don't have to care about District code any more.

This is very different from ORMA's assumption on how VPROMM code works. @PCDuc will find a way to reconcile the VPROMM table before we import it.

**Comment by geohacker** [comment]
Hi @PCDuc - we've imported the new admin layer and the issues you reported are all now fixed. http://openroads-vn.com/#/en/assets

Thank you for your help!
