### ISSUE TITLE
Repetition of same VPRoMMS IDs in different provinces

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#493]
- Many VPRoMMS IDs appear in many provinces at the same time (such as 212TH... in An Giang, Ba Ria-Vung, Bac Giang,...while they should be listed in Thanh Hoa province only)

**Comment by geohacker** [comment]
@PCDuc thank you for reporting. This is related to #492 - errors from admin boundary layer. Some codes are mismatched like we discovered a few months ago #381. Could you share a canonical list of provinces, districts, and their respective codes? 

cc @kai2ser @olafveerman @batpad

**Comment by geohacker** [comment]
These are also fixed now.
