### ISSUE TITLE
Fix a typo in Admin boundary code

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#510]
@geohacker Could you please fix a small typo in Admin boundary code that the code of Loc Ha district in Ha Tinh province (Pro_code: 42) is change from LA to LH. 
I've updated the change to these shape file https://1drv.ms/f/s!AlXoorZjtVf-3za8tKwS1Wfng2iN
Many thanks.
Related to issue #492

**Comment by geohacker** [comment]
Sure thing @PCDuc. The ORMA province code for Ha Tinh is 23. This is fixed now. 

Steps:
1. `select id, name_en, code from admin_boundaries where parent_id=465;`
2. Find Loc Ha id as 477.
3. `update admin_boundaries set code='LH' where id=477;`
