### ISSUE TITLE
Search function in both Assets page and Editor Page using Admin name should work in both VI and EN? 

### ISSUE THREAD

**Issue by Anhitc** [orma/openroads-vn-analytics#516]
![2018-11-02_101911](https://user-images.githubusercontent.com/39816763/47900318-0dfb0d80-deaf-11e8-9142-26dba13a8c54.png)
Search function in both Assets page and Editor Page using Admin name should work in both VI and EN? Now it just returned result when search for EN name in the both VI/EN interfaces

**Comment by geohacker** [comment]
The search seems to work fine in VI as well as EN. Could you double check? Thank you!

![image](https://user-images.githubusercontent.com/371666/47902276-c7ee7b80-dea7-11e8-9e4a-7c88d326a434.png)

**Comment by Anhitc** [comment]
Hi Sajad, Long time!
What I mean here is the text string: 
If you searched for: Thanh Hoa it is ok
But if you search for: Thanh Hóa it is not returning result as it is in the attached screenshot.
In most of the cases the user will type the VI word with all its "special" symbols and may not get the result they want.
And if taking out the VI "special" symbols, many result will became the same. 
Pls. do consider.
