### ISSUE TITLE
Assets page summary on total road length

### ISSUE THREAD

**Issue by Anhitc** [orma/openroads-vn-analytics#517]
![2018-11-02_150138](https://user-images.githubusercontent.com/39816763/47900830-dee59b80-deb0-11e8-80d8-5681f4a2b9cc.png)
The red box Can be changed to: 
Length(km) 
8110.15     8018.30 (98.87%)
WON         GPROMMS

**Comment by geohacker** [comment]
@Anhitc Are you suggesting that we can change the label "Road length" to just "Length"?

**Comment by geohacker** [comment]
@Anhitc Agree. I just made the change to make the Asset detail page say Road Length (ORMA) and Road Length (VPROMM) so it's more clear. Also truncated decimals to two.
