### ISSUE TITLE
Add the categorical values and pick colors for width, condition, and surface

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#53]
Right now, the color `stops` in our map styles are empty for `or_width`, `or_condition`, and `or_surface`. See: https://github.com/orma/openroads-vn-analytics/blob/develop/app/assets/scripts/utils/line-colors.js#L15

@olafveerman, can you fill in the valid values for these categorical fields, and assign colors to each? For example, if it's currently:

```
  'or_surface': {
    property: 'or_surface',
    type: 'categorical',
    stops: [
      [false, '#808080']
    ]
  }
```

make it

```
  'or_surface': {
    property: 'or_surface',
    type: 'categorical',
    stops: [
      ['earth', '#abcdef'],
      ['asphalt', '#123456'],
      ['concrete', '#456789']
    ]
  }
```

There's no need to keep the "`false`" `stop`; that was just a placeholder. Also, regarding roads that are _missing_ these properties, I don't think you can make a `stop` for them, don't worry about that for now; I'm addressing in https://github.com/orma/openroads-vn-analytics/issues/40.

**Comment by olafveerman** [comment]
From the Roads 2 spec, these are the categories:

```
  'condition': {
    property: 'condition',
    type: 'categorical',
    stops: [
      ['very poor', ''],
      ['poor', ''],
      ['fair', ''],
      ['good', ''],
      ['very good', '']
    ]
  },
  'surface': {
    property: 'surface',
    type: 'categorical',
    stops: [
      ['Cement Concrete', ''],
      ['Asphalt Concrete', ''],
      ['Surface Treatment', ''],
      ['Gravel', ''],
      ['Earth', ''],
      ['Macadam', ''],
      ['Cobblestone', ''],
      ['Other', '']
    ]
  }
```

In another document, the classifications are the same, but some of them are lumped together:

```
R: Cement
S: Asphalt
T: Treatment
U: Gravel, Macadam, Cobble Stone
V: Earth
```

**Comment by mileswwatkins** [comment]
Cool, can you submit this code in the coming week, making some color choices either on your own, or with the help of @ricardomestre?

**Comment by olafveerman** [comment]
Yes, I'm checking what the classification was they used in the end.

**Comment by mileswwatkins** [comment]
No categorical values set to be visualized anytime in the near future.

**Comment by geohacker** [comment]
Going to close this since we deemed this not needed in the near future.
