### ISSUE TITLE
Assets Dashboard interface: suggestions for improvement

### ISSUE THREAD

**Issue by olafveerman** [orma/openroads-vn-analytics#533]
Reported by Anh

* The Name of road and location need to be broken saving whole complete word in one line. And let’s use the complete Vietnamese name in both VI and EN interface
* The attributes can be logically grouped:  
  * IRI group
  * Road start and road end
  * Road Length (ORMA – GPROMM)
* The coordinate of start and end point (4 values) may not be shown here as it has limited used.  
* Province code, Road Number, Management level should be Interger the 2 digit should be take away

![image](https://user-images.githubusercontent.com/751330/49649733-fe17a180-f9f7-11e8-99a6-6f4f25e120d4.png)

**Comment by geohacker** [comment]
This is now implemented in v3.0.1. Closing.

**Comment by olafveerman** [comment]
![image](https://user-images.githubusercontent.com/751330/50029398-95fd2880-ffc0-11e8-9bbf-3f4e34bfefcd.png)
