### ISSUE TITLE
Do more" button is not functioning in Task

### ISSUE THREAD

**Issue by geohacker** [orma/openroads-vn-analytics#540]
From Duc:
> Do more" button is not functioning in Task

We require additional details to replicate the problem. Could give an example, screenshots, and steps to reproduce the issue? Thank you!

**Comment by olafveerman** [comment]
cc @PCDuc

**Comment by PCDuc** [comment]
Go to Task. Perform a Remove duplicate or Create intersection and Apply
The “Do more” button shows up but has no response when be clicked
![image](https://user-images.githubusercontent.com/31137016/53516563-31516480-3aff-11e9-8793-3a2e88bfa200.png)
