### ISSUE TITLE
[Bug][Deleting is not working]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#564]
Step 1 : http://openroads-vn.com/#/en/assets/road/214YD00001
Step 2 : Click Edit
Step 3 : Select Delete
Step 4 : Click Confirm 
=> Repeat to step 1 
Expected Result : Asset is deleted already
Actual Result : Asset is still there

**Comment by geohacker** [comment]
Fix in https://github.com/orma/openroads-vn-analytics/pull/579

**Comment by tailm1** [comment]
Please check again this bug, Deleted VProMMId still appear in suggestion div
![image](https://user-images.githubusercontent.com/38553180/53480758-684b5a00-3aae-11e9-82a6-b8e2e0c24b6b.png)

**Comment by tailm1** [comment]
Please show appropriate message instead. this is not "Page Not Found"
