### ISSUE TITLE
[Bug][Search Button is not working at the second time]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#566]
Step 1 : Go to asset Tab
Step 2 : Type 214YD00001 at VProMMs search box
Step 3 : Click Search Icon
=> Result appear
Step 4 : Click to Asset Tab again to go Overview page
Step 5 : click search icon again (Don't remove value in current search box)
Expected Result : The result is appear again
Actual Result : "No result available. Please refine your search"

**Comment by batpad** [comment]
Thank you for the clear report @tailm1 .

@geohacker - we should clear the search input whenever the user hits search. Not clearing it and then navigating between pages seems to cause the issue above. I think it would be most straightforward and consistent for the user if we just always clear the search input when the user hits search. I can take this on.
