### ISSUE TITLE
[Bug][Upload function doesn't work correctly]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#567]
Step 1 : Go to upload tab
Step 2 : Attach 214YD00014.zip
Expected result : If data is valid, asset should be added to the system. 
If not, an error dialog should be shown
Actual Result : New blank page is display
Note : Please refer attachment

[214YD00014.zip](https://github.com/orma/openroads-vn-analytics/files/2892559/214YD00014.zip)
![image](https://user-images.githubusercontent.com/38553180/53222467-7e1ce180-36a0-11e9-8bab-92bc6a772a23.png)

**Comment by geohacker** [comment]
@batpad let's return an error when the file type is not CSV.

**Comment by KPGeo** [comment]
@batpad @geohacker error replicated using Chrome on stable internet connection in the US. The resulting screen listed the VPROMMS ID (034HG00006) of the asset, but no attributes were added to the asset. 
<img width="338" alt="result on upload" src="https://user-images.githubusercontent.com/23564203/53369236-c5ada280-3918-11e9-95da-14ea62196f80.PNG">

Zip file contained csv with attributes in columns "AN" through "BN"

**Comment by geohacker** [comment]
@KPGeo thank you! Looks like what you're seeing is unrelated from this error reported by @tailm1. In this case IRI, distance, suspension, start coordinates, end coordinates, and time will be read at the time of property ingestion. The upload is successful. 

The error @tailm1 raised handled in v3.3.0.
