### ISSUE TITLE
[Bug][Upload tab is work incorrectly]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#569]
Step 1 : Go to Upload Tab
Step 2 : try to drop one file to outside of Road Properites and Road Geometries area
Expected Result : Nothing happen or the file is attached in page
Actual Result :  File Saving dialog is displayed
Please refer to my attachment
![image](https://user-images.githubusercontent.com/38553180/53223033-9d1c7300-36a2-11e9-89da-2db2694b6fc0.png)

**Comment by geohacker** [comment]
I'm unable to replicate this issue @tailm1. ORMA platform doesn't allow for file drop uploads, and hence this issue wouldn't occur. It is possible that your browser is allowing file drop and causing this behavior. 

Thank you for the ticket!

Here's a gif of the behavior:

![orma-upload](https://user-images.githubusercontent.com/371666/53236516-71a58280-36ba-11e9-9a09-1196783e02cb.gif)

**Comment by tailm1** [comment]
Hi @geohacker . "ORMA platform doesn't allow for file drop uploads, and hence this issue wouldn't occur"
You can try to drop a file to Upload box. the system allows actually. I still can see a downloading progress from your giff image. it's just different because of behavior of each browser. I'm using Chrome (Windows)

**Comment by geohacker** [comment]
Hi @tailm1 - If you drag and drop a file in an arbitrary part of the page, the browser may try to open it and view, or just download it. This is the default behaviour of the browser and not a bug in ORMA.

**Comment by tailm1** [comment]
Hi @geohacker, I understand what you mean but could you limit the effective area for that behavior like Facebook? only one specific area is effective once u drop a file
