### ISSUE TITLE
[Bug][Grid in Map Overlay is not working]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#573]
Step1 : Go to Editor Page 
Step 2 : Click on Map Overlays button 
Step 3 : Switch Grid option
Expected Result : something happens
Actual Result : Nothing happens and got a lot of errors from console tab
![image](https://user-images.githubusercontent.com/38553180/53224048-ea4e1400-36a5-11e9-9e23-785703ce427c.png)

**Comment by batpad** [comment]
@geohacker this looks like the same issue as https://github.com/orma/openroads-vn-analytics/issues/572 - i.e. 401 errors from Mapbox.

**Comment by geohacker** [comment]
This is also a legacy issue @batpad. Looking at the Mapbox account, I do not see this particular style. 
We should likely remove the grid functionality - it's not used as far as I understand.

cc @olafveerman
