### ISSUE TITLE
[Asset][System Redirect to wrong page after adding new asset]

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#576]
Click Asset -> Click any Provice -> Click District -> Click Add Asset -> Input data (ex: 180LS0002) and then click Save -> Click Add Asset button again 
-> System redirects user to the wrong page.
![image](https://user-images.githubusercontent.com/38553180/53227123-e921e480-36af-11e9-8104-5296236486c7.png)

**Comment by batpad** [comment]
Thank you @tailm1 .

@geohacker I am unable to reproduce exactly, but https://github.com/orma/openroads-vn-analytics/issues/583 seems really critical and causes all sorts of strange behaviour when adding assets to provinces that are not in the frontend list. Let's try and fix that as soon as possible and then re-test these. I can take that on.

**Comment by geohacker** [comment]
This is the expected behavior. The VPROMM ID `180LS0002` is invalid as it has only 9 digits.

There's also an alert showing this error:

![image](https://user-images.githubusercontent.com/371666/53234118-d827a200-36b4-11e9-8605-e5d03d4da455.png)

**Comment by tailm1** [comment]
@geohacker  you can try another successful case. 
Once you added successfully and then you click Add New Asset again. The system will redirect to home page

**Comment by tailm1** [comment]
@geohacker Please re-open this issue. I still can reproduce. You try to input with value 180LS00020.
