### ISSUE TITLE
[Multi Language Issue] Still show English in Vietnamese Mode

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#580]
Step 1 : Select Language : Vietnam
Step 2 : Go to http://openroads-vn.com/#/vi/assets/road/211TH00047 
Expectation : Show Vietnamese messages instead
![image](https://user-images.githubusercontent.com/38553180/53227798-e4f6c680-36b1-11e9-8a22-3c7132e859a7.png)

**Comment by geohacker** [comment]
This is a duplicate of #561. Thank you for the issue!

**Comment by tailm1** [comment]
Could you tell me your strategy to resolve this issue? I just log a sample case. There are a lot of items/labels hasn't translated in Vietnamese mode
