### ISSUE TITLE
Unable to Sort and Filtering in Asset Page 

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#582]
Go To Asset Page
Expectation : Users able to sort and filter admin/asset by click in column header

**Comment by geohacker** [comment]
This is duplicate of https://github.com/orma/openroads-vn-analytics/issues/520 - and is an enhancement we can consider for the next phase of work. Thank you for opening the issue!

**Comment by tailm1** [comment]
Please note that we expect filtering function for each column also.
