### ISSUE TITLE
(i)Loading icon is shown forever after click information icon

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#584]
Step 1 : Go to Editor Page
Step 2 : Select one asset
Step 3 : Click at Information Icon (i)
Expected Result : Show information 
Actual Result : The System keeps loading
![image](https://user-images.githubusercontent.com/38553180/53234297-cf899880-36c1-11e9-9472-ca9d34bd83a9.png)

**Comment by geohacker** [comment]
Thank you for the ticket!

This is a legacy issue as well. The info is being requested from Taginfo service. The ORMA specific tags are available in the manual. 

We will show meaningful message though https://github.com/orma/openroads-vn-iD/pull/61

**Comment by tailm1** [comment]
from the end-user side, it's still a bug with us. Please re-open this issue and mark it's won't fix or hard. I will discuss with Project Team about it later

**Comment by geohacker** [comment]
@tailm1 the loading icon will stop loading, and display the following message if documentation is unavailable:

![image](https://user-images.githubusercontent.com/371666/53321460-912ced00-38fe-11e9-898d-6e77512238cc.png)
