### ISSUE TITLE
VPRoMM ID validation in editing

### ISSUE THREAD

**Issue by tailm1** [orma/openroads-vn-analytics#596]
try to edit VPRoMM ID with invalid value. 
System is calling api without validation from front-end side. 
Expected Result : Meaningful message will be shown
![image](https://user-images.githubusercontent.com/38553180/53482489-de9d8b80-3ab1-11e9-835d-7c6dd41249b0.png)

**Comment by geohacker** [comment]
The front-end cannot do this type of validation because it's important to do this on the API. We can make the error message meaningful incase of a conflict.

**Comment by geohacker** [comment]
Fixed in #609

**Comment by geohacker** [comment]
A conflict will get the error message accurately. Any other error will also get proper error messages from the API.
