### ISSUE TITLE
The statistic in some provinces shows GPRoMMS length value but doesn't have any Field data

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#599]
Why does Quang Binh show GPRoMMS length value but doesn't have any Field data? The same situation happened to Bac Kan, Cao Bang, Lao Cai, Thua Thien Hue, Ninh Binh, Tuyen Quang, Yen Bai.
![image](https://user-images.githubusercontent.com/31137016/53516837-d4a27980-3aff-11e9-8f28-01c8e339a198.png)

**Comment by geohacker** [comment]
Related to https://github.com/orma/openroads-vn-analytics/issues/600

**Comment by geohacker** [comment]
Related to the length calculation error fixed in https://github.com/orma/openroads-vn-tiler/pull/75
