### ISSUE TITLE
Re-implement maintaining of zoom and center, when switching maps

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#60]
I git revert'ed this merge, because it caused a significant UI reversion and loss of several commits' work: https://github.com/orma/openroads-vn-analytics/pull/59/commits/2d82fb14446f1de0dadf2c317a86c09d51535284

Re-implement https://github.com/orma/openroads-vn-analytics/issues/20

**Comment by maxgrossman** [comment]
re-implemented with 1913e4a
