### ISSUE TITLE
ORMA only takes length of one link/section as "Road length (ORMA)"

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#600]
Even if a VPRoMMS has several links/sections, ORMA only takes length of one link/section as "Road length (ORMA)" (GPRoMMS length) which is incorrect.
![image](https://user-images.githubusercontent.com/31137016/53518647-10d7d900-3b04-11e9-8a3b-f685f03337a2.png)
Length of way ID 508733 is used in this case.
![image](https://user-images.githubusercontent.com/31137016/53518810-69a77180-3b04-11e9-9d28-ef060a6689c0.png)

**Comment by geohacker** [comment]
Looks like a summation error. Will inspect.

**Comment by geohacker** [comment]
This was a summation error and fixed in https://github.com/orma/openroads-vn-tiler/pull/75
