### ISSUE TITLE
To-fix tool suggests user to remove duplicates or create intersection but only shows one single road

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#601]
To-fix tool in Task suggests user to remove duplicates or create intersection but only shows one single road.  The to-fix action can be done with only one road.
![image](https://user-images.githubusercontent.com/31137016/53522295-a37c7600-3b0c-11e9-8fee-55362d28d91f.png)

**Comment by geohacker** [comment]
@PCDuc Could you share the Task ID? It's not clear from your screenshot. The task ID is above 'Prepare workflow' text.

**Comment by PCDuc** [comment]
@geohacker The task ID is #37450230
Thanks

**Comment by geohacker** [comment]
This should be fixed in https://github.com/orma/openroads-vn-api/pull/190 - this in case there are geometries that got deleted after the task was created.  cc @batpad
