### ISSUE TITLE
 How to quickly check the length of a GPRoMMS?

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#604]
Nam Dinh province feedback that after tracing many roads on ORMA, they need to wait 24h for road lengths are calculated, then check all previous roads one by one to see if the lengths are reasonable and do revision if needed, then repeat the process. This workflow is quite cumbersome for them. Is there any way to quickly check the length of a GPRoMMS? A ruler tool may help in this case.
At the moment, I instructed them to use QGIS to quickly check the length.

**Comment by geohacker** [comment]
Fixed in 3.4.0 https://github.com/orma/openroads-vn-analytics/pull/610
The length is now calculated immediately on the front-end. Note that this is not added up to the stats at the province and district levels. Those length stats are still calculated once a day.
