### ISSUE TITLE
Inconsistent column order in Section tab

### ISSUE THREAD

**Issue by PCDuc** [orma/openroads-vn-analytics#605]
Go to Asset > a collected VPRoMMS ID > Section tab
The order of attribute column is inconsistent between different VPRoMMS IDs
![image](https://user-images.githubusercontent.com/31137016/53525058-8c8d5200-3b13-11e9-9db1-bf73cfcad46c.png)

![image](https://user-images.githubusercontent.com/31137016/53525072-91520600-3b13-11e9-99dd-31178bdbfaf3.png)

**Comment by geohacker** [comment]
Fixed in https://github.com/orma/openroads-vn-analytics/pull/607. The list is ordered alphabetically based on the label.
