### ISSUE TITLE
Add admin and road search functionality

### ISSUE THREAD

**Issue by maxgrossman** [orma/openroads-vn-analytics#67]
- allow users to search roads by id
- trigger zoom to admin boundary by search for an admin boundary

**Comment by mileswwatkins** [comment]
Make sure this includes district and commune shapes.

**Comment by mileswwatkins** [comment]
To do this, you may need to add an API endpoint that surfaces the admin areas. Feel free to look to ORMA–Philippines as an example of what the request/response pattern could be.

**Comment by maxgrossman** [comment]
closed with #97 merge to dev.
