### ISSUE TITLE
Add analytics indicator of which major properties exist on a VPRoMMS road ID

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#70]
- width
- surface type
- IRI

**Comment by mileswwatkins** [comment]
May require adding a new database table; look at `stats` table in ORMA–Philippines, for an example.

**Comment by mileswwatkins** [comment]
So, I don't think this requires a new table. If we're going to populate the dashboard rows using the `road-properties` table (as is planned in https://github.com/orma/openroads-vn-analytics/issues/113), then we can just do a check as to whether these exist in the JSONB `properties` object for that road ID.

**Comment by maxgrossman** [comment]
We have properties visible in dropdown made in #112, so going to close this for now.
