### ISSUE TITLE
Add ToFix interface

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#76]

**Comment by olafveerman** [comment]
This was implemented.
![demo2](https://user-images.githubusercontent.com/751330/31318975-07f609ee-ac29-11e7-9f3d-fefac416a2d9.gif)

![demo](https://user-images.githubusercontent.com/751330/31318974-07f3fd16-ac29-11e7-8f22-6a364ee5d8bb.gif)
