### ISSUE TITLE
Add link to RAM

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#80]
Details forthcoming, in 9/11/2017 email to Sarah.

**Comment by mileswwatkins** [comment]
Keith:

> I believe what we agreed was that there would be a way to output data from ORMA that we could then ingest it in a RAM instance as needed. Perhaps there would be a button with a link to the RAM tool, and an explanation about the tool, required inputs, etc, but that full integration between the two was not feasible in the available time for Phase 1 (since there are still other issues with RAM), and that the utility would be dependent on the initial quality of the data as stored in the CMS.

Olaf:

> The best thing we can do for ORMA - RAM integration is to focus workflows that improve the routability of the dataset, and generating exports that are ready to be imported into RAM.

**Comment by mileswwatkins** [comment]
Our routable output for this phase is going to be focused on Charles's RONET/CSV-WKT output, rather than RAM-compatible OSM XML dumps. Bumping to phase 2, per conversation with Sarah.

**Comment by mileswwatkins** [comment]
For this phase, add this basic interface to direct users to RAM.

**Comment by geohacker** [comment]
We may add the link to CBA when it's ready.
