### ISSUE TITLE
Document and diagram workflows and system

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#82]
Include system requirements, if applicable. Also include annual operations and maintenance cost estimates for the platform, including any for-pay data provision or hosted services.

**Comment by mileswwatkins** [comment]
Done:

- Architecture diagram created https://docs.google.com/a/developmentseed.org/drawings/d/1wuHYpjMYsshBaVNj6mykR42ln7ApLrY-OM6jsHiuZA8/edit?usp=sharing
- API documentation generated from comments

Remaining:

- Create re/deployment walkthrough
- Re/write READMEs for the main ORMA repos

**Comment by olafveerman** [comment]
Here's another write-up based on the architecture diagram posted in the above comment: https://docs.google.com/a/developmentseed.org/document/d/1FRzJOsu38i7fagJLkkE-gaXoHV5FMYHicEYsCuDOU0c/edit?usp=sharing

**Comment by olafveerman** [comment]
![image](https://user-images.githubusercontent.com/751330/31319008-67e69d00-ac29-11e7-999e-6b7f082d3a3c.png)

**Comment by mileswwatkins** [comment]
@olafveerman, updating the READMEs (the only remaining part of this ticket) is something that could be delegated to any of several members of the team.

**Comment by mileswwatkins** [comment]
![orma vn phase 2 architecture](https://user-images.githubusercontent.com/4959135/33675125-8936e5da-da7f-11e7-8853-1f3552f1c2b5.png)

**Comment by mileswwatkins** [comment]
https://github.com/orma/openroads-vn-analytics/commit/20a8eea5b3c3d66b6a661b9b8f50aaeef35144c8

**Comment by mileswwatkins** [comment]
https://github.com/orma/openroads-vn-tiler/commit/88e96f4df04dd073879841ec5cc85e6d4ae900d6

**Comment by mileswwatkins** [comment]
https://github.com/orma/openroads-vn-iD/commit/b9a89ad54ea603354023e86d6d40ff44172d7990

**Comment by mileswwatkins** [comment]
https://github.com/orma/openroads-vn-api/commit/7c7159b20b1be63bf2c3f4cd93cce0be5330b781

**Comment by mileswwatkins** [comment]
bam
