### ISSUE TITLE
Add road-coalescing suggestion functionality to ToFix

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#87]
If multiple roads in the "canonical geometries" run parallel and appear to be duplicates, create a suggestion for the user of ToFix to either:

- pick one as the most-correct, and throw out the other geometries
- merge all of them into one road (create a buffer around each line, dissolve buffers together, find center-line as the new road)

Either way, we'll have to make sure that the new road is tagged with the appropriate VPRoMMS road ID.

We did somewhat-similar work on OR Philippines; check with @mileswwatkins and @kamicut about this. @matthewhanson is also a resource on this.

This should be accessible in the ToFix interface #76

The purpose of this is to support making a routable road network.

**Comment by dereklieu** [comment]
Partially implemented, and a further approach (potential) is documented in #170
