### ISSUE TITLE
Add HTTP basic authentication to access website

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#88]
Does not need individual users or accounts. API authentication will come after Phase 1.

**Comment by danielfdsilva** [comment]
@mileswwatkins if there's no api auth nor user account, we're using http basic auth, right? Isn't that setup on aws when you deploy the website?

**Comment by mileswwatkins** [comment]
Yup, this would be HTTP basic auth. I've never been able to deploy it on a public S3 website; would you be able to do it, or work with @matthewhanson on how to make it work?

**Comment by danielfdsilva** [comment]
I don't think the S3 buckets support authentication. I think you need to use a server for that, or implement some sort of alternative in the app, but I guess it always need to be backed up by a server. Could this be deployed to EC2 for instance?

**Comment by mileswwatkins** [comment]
<img width="1033" alt="screen shot 2017-10-03 at 08 40 03" src="https://user-images.githubusercontent.com/4959135/31125567-b10cb1ca-a816-11e7-8812-898a11ca0aca.png">

So Daniel will stand up a cheap EC2 later this week to serve this. No integration with @matthewhanson's Kes script for now, just a standalone deploy.

cc @olafveerman

**Comment by olafveerman** [comment]
@danielfdsilva When you set this up, please serve the frontend over HTTP. This is temporary, until we serve all assets over HTTPS.

**Comment by olafveerman** [comment]
This is live on the staging environment. Closing
