### ISSUE TITLE
Add Kes CI-deploy

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#90]
Wrapping up https://github.com/orma/openroads-vn-api/pull/4#issuecomment-330274492

I chewed the tagging over; how about we always deploy `latest` with Kes, but we tag and push images using the current date? Would be good enough for rollback purposes, I think.

**Comment by mileswwatkins** [comment]
Oh, and by the way, I think I'd said that the database needs to be exposed to the Internet. @kamicut suggested that this was a bad idea, and so I'll aim for something like this instead https://github.com/orma/openroads-vn-analytics/issues/93

**Comment by mileswwatkins** [comment]
cc @matthewhanson, for reference

**Comment by mileswwatkins** [comment]
It'd be ideal for this deployment to execute any new `*.sql` migrations in `openroads-vn-api`'s `/db/sql` directory. But this can be done manually, if it's too much of a hassle.

**Comment by matthewhanson** [comment]
kes deployment is configured to work on CircleCI on the openroads-vn-api repo. On merge to master the entire system will be deployed. 
This does not include database migration which will have to be done manually, but is covered by issue #101
