### ISSUE TITLE
Move API documentation generation to docker-compose

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#91]
This will enable better CI deployment

cc @scisco

**Comment by mileswwatkins** [comment]
@matthewhanson, bumping this ticket to you.

Basically, the documentation-generation and -pushing-to-production was not performed by @scisco's original Kes script. Make sure that this is accomplished somewhere, so that the documentation hosted at the `/` API endpoint in production is updated by CI.

This is a lower priority than your other work, but still needs to be done by the end of the week.

**Comment by matthewhanson** [comment]
When the API docker image is built it generates the documentation so it can be served at the root API. Deployed to AWS prod
