### ISSUE TITLE
Move workers to same AWS private subnet as the database, so they can access

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#93]
Info for @matthewhanson's implementation:

One of the deliverables for this phase is to rely less on hosted services, and make sure all code is Dockerized. I believe the end client will want to deploy the workers, API, and DB on a single local server (although S3 would still be used to host static files, and S3 or GH Pages would be used to host the front-end).

[This is how the architecture stood](https://user-images.githubusercontent.com/4959135/28737988-0d3e5e1c-73bf-11e7-91c3-0c3e645b3566.jpg) when we wrapped up the previous phase of work, mostly set up by @kamicut and myself:

- cron'd workers on Hyper.sh
- API in a Docker container on Heroku
- hosted DB on Heroku
- raster tiles, data dumps, and static website on S3
- vector tiles hosted on Mapbox

@scisco has [taken care](https://github.com/orma/openroads-vn-api/pull/4#issuecomment-330274492) of doing an ECS deployment of our API and DB, which are in a Docker Compose file; these will supersede the Heroku API and DB, much more closely mimicking a local-server Compose deployment by the client.

The workers need to be able to directly access the database, to execute a dump of all road geometries and properties present therein. There are three workers currently (you can see using `hyper cron ls` and `hyper ps -a` with the Devseed login), although there may be more in the future. You can ask @kamicut if you have questions about them:

1. `developmentseed/openroads-tiler` creates (raster?) tiles of the roads in the database, and stores them in an S3
2. `developmentseed/openroads-tilemap` serves the tiles created above, from the S3, for use in the Editor view, a deployment of [iD](https://wiki.openstreetmap.org/wiki/ID)
3. `developmentseed/openroads-vn-tiler` creates vector tiles for display in the Explore view; these are uploaded to and served by Mapbox. It also makes some road-by-road statistics, and puts by-admin-area GeoJSON dumps up onto S3.

The environment variables for the above are generally AWS creds (standard naming), as well as source/destination for the files (so S3 container, or Mapbox account creds) and database URL. I haven't touched the env vars for the first two; questions on those could go to @kamicut.

So, options (mostly c/o @kamicut):

1. Add a password to the Postgres and open up the ECS'd database's port to the internet. @kamicut has warned against this, since he doesn't think that a password is sufficient hardening, but it could be a solution for this phase. @scisco is in favor of this. It would make things easier, since then the workers could be hosted anywhere, but it also doesn't fit how the client's deployment will go.
2. Figure out some way to regularly dump the database to S3, so the workers could just access the database _indirectly_. But this seems less true to the client's use case, would probably require a small process to execute the dump anyway, and would mean that the workers wouldn't have super-up-to-date database information.
3. Create a private AWS subnet, to allow the database port (exposed on `5433` on the Docker host, per the Compose file) to be accessible to the workers. This would also entail deploying a new EC2 to `docker run` the workers, utilizing that EC2's system cron to schedule the runs.
4. Identify the EC2 that hosts the DB/API ECS, and just cron-run the Dockerized worker code on that EC2 itself, no need for a subnet. This sounds most similar to the client's end-use, but a little more haphazard than option 3, deployment-wise.

**Comment by mileswwatkins** [comment]
cc @dereklieu, since your conflation/snapping worker will have to fit into this setup

**Comment by matthewhanson** [comment]
On AWS the workers now run as separate tasks on an ECS cluster, which in this case is just a single EC2 but could be scaled to be on separate instances if needed in the future.
