### ISSUE TITLE
Point workers and front-end at the new API and database URIs

### ISSUE THREAD

**Issue by mileswwatkins** [orma/openroads-vn-analytics#95]
After https://github.com/orma/openroads-vn-analytics/issues/93

The deployed workers that use database dumps will need to be updated, to point at the new database URI. They can continue to use the same S3 bucket for reads/writes of the tiles and dumps.

The deployed front-end (static, via GH pages) will need to be pointed at the new API, by updating the config.

@olafveerman or @kamicut may be able to help with questions on this.

**Comment by matthewhanson** [comment]
The workers have been updated. For development the docker-compose file will point them to a database running on a locally run container. On prod, kes sets the envvar on the worker containers to point to the RDS instance.

So just the front-end needs to be updated @olafveerman
