### ISSUE TITLE
Explore Mapbox linematch as candidate for conflation engine

### ISSUE THREAD

**Issue by dereklieu** [orma/openroads-vn-analytics#96]
I ran the provincial data dump through linematch. To find segments that had overlap, I individually ran each segment through, comparing it to the network minus the segment itself. Then I created a geojson file that contained segments where over 50% of the segment length is duplicated. 

**Here's the entire network.**

<img width="685" alt="screen shot 2017-09-19 at 2 05 33 pm" src="https://user-images.githubusercontent.com/1590802/30608275-d4c51872-9d45-11e7-99bf-53aaebca13af.png">

**Here are the portions that have 50% of their length match other segments.**

<img width="677" alt="screen shot 2017-09-19 at 2 05 58 pm" src="https://user-images.githubusercontent.com/1590802/30608286-ded23f02-9d45-11e7-8fb5-ee5bfc409b32.png">

**I ran it again, but this time preserved the lines that have just over 10% of their length match other segments.**

<img width="663" alt="screen shot 2017-09-19 at 2 26 45 pm" src="https://user-images.githubusercontent.com/1590802/30608524-ade32112-9d46-11e7-9366-b3aadfd1e1fb.png">

I used a `0.001` threshold for these. I put the code at https://github.com/dereklieu/orma-vietnam-conflation.

**Comment by dereklieu** [comment]
I think the initial results are promising, but for performance reasons, I think it makes sense to fork and modify linematch to better suite our needs.

Currently, linematch is built to compare two networks and expose the parts that are unique. When it finds a duplicate segment, it throws the metadata about that segment out. As a result, I had to run each segment individually against the whole, which is very costly, as linematch needs to index the entire network each time.

I need to make the following modifications:
- [ ] find and store the duplicated segments
- [ ] keep metadata on the duplicated segments, particularly the primary key, so that we can use them later in the task manager.

**Comment by matthewhanson** [comment]
@dereklieu You may have already discovered this, but you can insert any type of data into rbush index in addition to the bbox for each line segment. so if you fork this you can insert the metadata then get it back when it queries for close segments.
https://github.com/mapbox/linematch/blob/master/index.js#L62

**Comment by dereklieu** [comment]
Nice, good to have confirmation of that, since that's pretty much the plan.

**Comment by dereklieu** [comment]
I've made the necessary modifications to linematch in my fork at https://github.com/dereklieu/networkmatch. Now going to switch my demo over to the forked version to test it against the same data set.

**Comment by dereklieu** [comment]
I updated my [demo](https://github.com/dereklieu/orma-vietnam-conflation) to use the new repo. The result is much, much faster. In addition, the metadata contained now allows you to reference the the matching features, which makes for more useful metadata (ie knowing that 2 roads match at some segments, vs knowing that 4 roads match).

**Comment by dereklieu** [comment]
Closing this as I have what I need to start building out our actual to-fix solution.
